
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const MarketStatus = {
  ACTIVE: 'ACTIVE',
  CLOSED: 'CLOSED',
  RESOLVED: 'RESOLVED'
} as const

export type MarketStatus = (typeof MarketStatus)[keyof typeof MarketStatus]


export const TradeSide = {
  BUY: 'BUY',
  SELL: 'SELL'
} as const

export type TradeSide = (typeof TradeSide)[keyof typeof TradeSide]


export const SignalType = {
  COPY_TRADE: 'COPY_TRADE',
  PATTERN_MATCH: 'PATTERN_MATCH',
  MANUAL: 'MANUAL'
} as const

export type SignalType = (typeof SignalType)[keyof typeof SignalType]
