
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `IngestionCursor` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model IngestionCursor
 * 
 */
export type IngestionCursorModel = runtime.Types.Result.DefaultSelection<Prisma.$IngestionCursorPayload>

export type AggregateIngestionCursor = {
  _count: IngestionCursorCountAggregateOutputType | null
  _min: IngestionCursorMinAggregateOutputType | null
  _max: IngestionCursorMaxAggregateOutputType | null
}

export type IngestionCursorMinAggregateOutputType = {
  key: string | null
  cursor: string | null
  updatedAt: Date | null
}

export type IngestionCursorMaxAggregateOutputType = {
  key: string | null
  cursor: string | null
  updatedAt: Date | null
}

export type IngestionCursorCountAggregateOutputType = {
  key: number
  cursor: number
  updatedAt: number
  _all: number
}


export type IngestionCursorMinAggregateInputType = {
  key?: true
  cursor?: true
  updatedAt?: true
}

export type IngestionCursorMaxAggregateInputType = {
  key?: true
  cursor?: true
  updatedAt?: true
}

export type IngestionCursorCountAggregateInputType = {
  key?: true
  cursor?: true
  updatedAt?: true
  _all?: true
}

export type IngestionCursorAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which IngestionCursor to aggregate.
   */
  where?: Prisma.IngestionCursorWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of IngestionCursors to fetch.
   */
  orderBy?: Prisma.IngestionCursorOrderByWithRelationInput | Prisma.IngestionCursorOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.IngestionCursorWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` IngestionCursors from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` IngestionCursors.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned IngestionCursors
  **/
  _count?: true | IngestionCursorCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: IngestionCursorMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: IngestionCursorMaxAggregateInputType
}

export type GetIngestionCursorAggregateType<T extends IngestionCursorAggregateArgs> = {
      [P in keyof T & keyof AggregateIngestionCursor]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateIngestionCursor[P]>
    : Prisma.GetScalarType<T[P], AggregateIngestionCursor[P]>
}




export type IngestionCursorGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.IngestionCursorWhereInput
  orderBy?: Prisma.IngestionCursorOrderByWithAggregationInput | Prisma.IngestionCursorOrderByWithAggregationInput[]
  by: Prisma.IngestionCursorScalarFieldEnum[] | Prisma.IngestionCursorScalarFieldEnum
  having?: Prisma.IngestionCursorScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: IngestionCursorCountAggregateInputType | true
  _min?: IngestionCursorMinAggregateInputType
  _max?: IngestionCursorMaxAggregateInputType
}

export type IngestionCursorGroupByOutputType = {
  key: string
  cursor: string
  updatedAt: Date
  _count: IngestionCursorCountAggregateOutputType | null
  _min: IngestionCursorMinAggregateOutputType | null
  _max: IngestionCursorMaxAggregateOutputType | null
}

type GetIngestionCursorGroupByPayload<T extends IngestionCursorGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<IngestionCursorGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof IngestionCursorGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], IngestionCursorGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], IngestionCursorGroupByOutputType[P]>
      }
    >
  >



export type IngestionCursorWhereInput = {
  AND?: Prisma.IngestionCursorWhereInput | Prisma.IngestionCursorWhereInput[]
  OR?: Prisma.IngestionCursorWhereInput[]
  NOT?: Prisma.IngestionCursorWhereInput | Prisma.IngestionCursorWhereInput[]
  key?: Prisma.StringFilter<"IngestionCursor"> | string
  cursor?: Prisma.StringFilter<"IngestionCursor"> | string
  updatedAt?: Prisma.DateTimeFilter<"IngestionCursor"> | Date | string
}

export type IngestionCursorOrderByWithRelationInput = {
  key?: Prisma.SortOrder
  cursor?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type IngestionCursorWhereUniqueInput = Prisma.AtLeast<{
  key?: string
  AND?: Prisma.IngestionCursorWhereInput | Prisma.IngestionCursorWhereInput[]
  OR?: Prisma.IngestionCursorWhereInput[]
  NOT?: Prisma.IngestionCursorWhereInput | Prisma.IngestionCursorWhereInput[]
  cursor?: Prisma.StringFilter<"IngestionCursor"> | string
  updatedAt?: Prisma.DateTimeFilter<"IngestionCursor"> | Date | string
}, "key">

export type IngestionCursorOrderByWithAggregationInput = {
  key?: Prisma.SortOrder
  cursor?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.IngestionCursorCountOrderByAggregateInput
  _max?: Prisma.IngestionCursorMaxOrderByAggregateInput
  _min?: Prisma.IngestionCursorMinOrderByAggregateInput
}

export type IngestionCursorScalarWhereWithAggregatesInput = {
  AND?: Prisma.IngestionCursorScalarWhereWithAggregatesInput | Prisma.IngestionCursorScalarWhereWithAggregatesInput[]
  OR?: Prisma.IngestionCursorScalarWhereWithAggregatesInput[]
  NOT?: Prisma.IngestionCursorScalarWhereWithAggregatesInput | Prisma.IngestionCursorScalarWhereWithAggregatesInput[]
  key?: Prisma.StringWithAggregatesFilter<"IngestionCursor"> | string
  cursor?: Prisma.StringWithAggregatesFilter<"IngestionCursor"> | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"IngestionCursor"> | Date | string
}

export type IngestionCursorCreateInput = {
  key: string
  cursor: string
  updatedAt?: Date | string
}

export type IngestionCursorUncheckedCreateInput = {
  key: string
  cursor: string
  updatedAt?: Date | string
}

export type IngestionCursorUpdateInput = {
  key?: Prisma.StringFieldUpdateOperationsInput | string
  cursor?: Prisma.StringFieldUpdateOperationsInput | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type IngestionCursorUncheckedUpdateInput = {
  key?: Prisma.StringFieldUpdateOperationsInput | string
  cursor?: Prisma.StringFieldUpdateOperationsInput | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type IngestionCursorCreateManyInput = {
  key: string
  cursor: string
  updatedAt?: Date | string
}

export type IngestionCursorUpdateManyMutationInput = {
  key?: Prisma.StringFieldUpdateOperationsInput | string
  cursor?: Prisma.StringFieldUpdateOperationsInput | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type IngestionCursorUncheckedUpdateManyInput = {
  key?: Prisma.StringFieldUpdateOperationsInput | string
  cursor?: Prisma.StringFieldUpdateOperationsInput | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type IngestionCursorCountOrderByAggregateInput = {
  key?: Prisma.SortOrder
  cursor?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type IngestionCursorMaxOrderByAggregateInput = {
  key?: Prisma.SortOrder
  cursor?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type IngestionCursorMinOrderByAggregateInput = {
  key?: Prisma.SortOrder
  cursor?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}



export type IngestionCursorSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  key?: boolean
  cursor?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["ingestionCursor"]>

export type IngestionCursorSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  key?: boolean
  cursor?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["ingestionCursor"]>

export type IngestionCursorSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  key?: boolean
  cursor?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["ingestionCursor"]>

export type IngestionCursorSelectScalar = {
  key?: boolean
  cursor?: boolean
  updatedAt?: boolean
}

export type IngestionCursorOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"key" | "cursor" | "updatedAt", ExtArgs["result"]["ingestionCursor"]>

export type $IngestionCursorPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "IngestionCursor"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    key: string
    cursor: string
    updatedAt: Date
  }, ExtArgs["result"]["ingestionCursor"]>
  composites: {}
}

export type IngestionCursorGetPayload<S extends boolean | null | undefined | IngestionCursorDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$IngestionCursorPayload, S>

export type IngestionCursorCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<IngestionCursorFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: IngestionCursorCountAggregateInputType | true
  }

export interface IngestionCursorDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['IngestionCursor'], meta: { name: 'IngestionCursor' } }
  /**
   * Find zero or one IngestionCursor that matches the filter.
   * @param {IngestionCursorFindUniqueArgs} args - Arguments to find a IngestionCursor
   * @example
   * // Get one IngestionCursor
   * const ingestionCursor = await prisma.ingestionCursor.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends IngestionCursorFindUniqueArgs>(args: Prisma.SelectSubset<T, IngestionCursorFindUniqueArgs<ExtArgs>>): Prisma.Prisma__IngestionCursorClient<runtime.Types.Result.GetResult<Prisma.$IngestionCursorPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one IngestionCursor that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {IngestionCursorFindUniqueOrThrowArgs} args - Arguments to find a IngestionCursor
   * @example
   * // Get one IngestionCursor
   * const ingestionCursor = await prisma.ingestionCursor.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends IngestionCursorFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, IngestionCursorFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__IngestionCursorClient<runtime.Types.Result.GetResult<Prisma.$IngestionCursorPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first IngestionCursor that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {IngestionCursorFindFirstArgs} args - Arguments to find a IngestionCursor
   * @example
   * // Get one IngestionCursor
   * const ingestionCursor = await prisma.ingestionCursor.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends IngestionCursorFindFirstArgs>(args?: Prisma.SelectSubset<T, IngestionCursorFindFirstArgs<ExtArgs>>): Prisma.Prisma__IngestionCursorClient<runtime.Types.Result.GetResult<Prisma.$IngestionCursorPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first IngestionCursor that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {IngestionCursorFindFirstOrThrowArgs} args - Arguments to find a IngestionCursor
   * @example
   * // Get one IngestionCursor
   * const ingestionCursor = await prisma.ingestionCursor.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends IngestionCursorFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, IngestionCursorFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__IngestionCursorClient<runtime.Types.Result.GetResult<Prisma.$IngestionCursorPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more IngestionCursors that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {IngestionCursorFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all IngestionCursors
   * const ingestionCursors = await prisma.ingestionCursor.findMany()
   * 
   * // Get first 10 IngestionCursors
   * const ingestionCursors = await prisma.ingestionCursor.findMany({ take: 10 })
   * 
   * // Only select the `key`
   * const ingestionCursorWithKeyOnly = await prisma.ingestionCursor.findMany({ select: { key: true } })
   * 
   */
  findMany<T extends IngestionCursorFindManyArgs>(args?: Prisma.SelectSubset<T, IngestionCursorFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$IngestionCursorPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a IngestionCursor.
   * @param {IngestionCursorCreateArgs} args - Arguments to create a IngestionCursor.
   * @example
   * // Create one IngestionCursor
   * const IngestionCursor = await prisma.ingestionCursor.create({
   *   data: {
   *     // ... data to create a IngestionCursor
   *   }
   * })
   * 
   */
  create<T extends IngestionCursorCreateArgs>(args: Prisma.SelectSubset<T, IngestionCursorCreateArgs<ExtArgs>>): Prisma.Prisma__IngestionCursorClient<runtime.Types.Result.GetResult<Prisma.$IngestionCursorPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many IngestionCursors.
   * @param {IngestionCursorCreateManyArgs} args - Arguments to create many IngestionCursors.
   * @example
   * // Create many IngestionCursors
   * const ingestionCursor = await prisma.ingestionCursor.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends IngestionCursorCreateManyArgs>(args?: Prisma.SelectSubset<T, IngestionCursorCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many IngestionCursors and returns the data saved in the database.
   * @param {IngestionCursorCreateManyAndReturnArgs} args - Arguments to create many IngestionCursors.
   * @example
   * // Create many IngestionCursors
   * const ingestionCursor = await prisma.ingestionCursor.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many IngestionCursors and only return the `key`
   * const ingestionCursorWithKeyOnly = await prisma.ingestionCursor.createManyAndReturn({
   *   select: { key: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends IngestionCursorCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, IngestionCursorCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$IngestionCursorPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a IngestionCursor.
   * @param {IngestionCursorDeleteArgs} args - Arguments to delete one IngestionCursor.
   * @example
   * // Delete one IngestionCursor
   * const IngestionCursor = await prisma.ingestionCursor.delete({
   *   where: {
   *     // ... filter to delete one IngestionCursor
   *   }
   * })
   * 
   */
  delete<T extends IngestionCursorDeleteArgs>(args: Prisma.SelectSubset<T, IngestionCursorDeleteArgs<ExtArgs>>): Prisma.Prisma__IngestionCursorClient<runtime.Types.Result.GetResult<Prisma.$IngestionCursorPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one IngestionCursor.
   * @param {IngestionCursorUpdateArgs} args - Arguments to update one IngestionCursor.
   * @example
   * // Update one IngestionCursor
   * const ingestionCursor = await prisma.ingestionCursor.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends IngestionCursorUpdateArgs>(args: Prisma.SelectSubset<T, IngestionCursorUpdateArgs<ExtArgs>>): Prisma.Prisma__IngestionCursorClient<runtime.Types.Result.GetResult<Prisma.$IngestionCursorPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more IngestionCursors.
   * @param {IngestionCursorDeleteManyArgs} args - Arguments to filter IngestionCursors to delete.
   * @example
   * // Delete a few IngestionCursors
   * const { count } = await prisma.ingestionCursor.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends IngestionCursorDeleteManyArgs>(args?: Prisma.SelectSubset<T, IngestionCursorDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more IngestionCursors.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {IngestionCursorUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many IngestionCursors
   * const ingestionCursor = await prisma.ingestionCursor.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends IngestionCursorUpdateManyArgs>(args: Prisma.SelectSubset<T, IngestionCursorUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more IngestionCursors and returns the data updated in the database.
   * @param {IngestionCursorUpdateManyAndReturnArgs} args - Arguments to update many IngestionCursors.
   * @example
   * // Update many IngestionCursors
   * const ingestionCursor = await prisma.ingestionCursor.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more IngestionCursors and only return the `key`
   * const ingestionCursorWithKeyOnly = await prisma.ingestionCursor.updateManyAndReturn({
   *   select: { key: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends IngestionCursorUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, IngestionCursorUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$IngestionCursorPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one IngestionCursor.
   * @param {IngestionCursorUpsertArgs} args - Arguments to update or create a IngestionCursor.
   * @example
   * // Update or create a IngestionCursor
   * const ingestionCursor = await prisma.ingestionCursor.upsert({
   *   create: {
   *     // ... data to create a IngestionCursor
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the IngestionCursor we want to update
   *   }
   * })
   */
  upsert<T extends IngestionCursorUpsertArgs>(args: Prisma.SelectSubset<T, IngestionCursorUpsertArgs<ExtArgs>>): Prisma.Prisma__IngestionCursorClient<runtime.Types.Result.GetResult<Prisma.$IngestionCursorPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of IngestionCursors.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {IngestionCursorCountArgs} args - Arguments to filter IngestionCursors to count.
   * @example
   * // Count the number of IngestionCursors
   * const count = await prisma.ingestionCursor.count({
   *   where: {
   *     // ... the filter for the IngestionCursors we want to count
   *   }
   * })
  **/
  count<T extends IngestionCursorCountArgs>(
    args?: Prisma.Subset<T, IngestionCursorCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], IngestionCursorCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a IngestionCursor.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {IngestionCursorAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends IngestionCursorAggregateArgs>(args: Prisma.Subset<T, IngestionCursorAggregateArgs>): Prisma.PrismaPromise<GetIngestionCursorAggregateType<T>>

  /**
   * Group by IngestionCursor.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {IngestionCursorGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends IngestionCursorGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: IngestionCursorGroupByArgs['orderBy'] }
      : { orderBy?: IngestionCursorGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, IngestionCursorGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetIngestionCursorGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the IngestionCursor model
 */
readonly fields: IngestionCursorFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for IngestionCursor.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__IngestionCursorClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the IngestionCursor model
 */
export interface IngestionCursorFieldRefs {
  readonly key: Prisma.FieldRef<"IngestionCursor", 'String'>
  readonly cursor: Prisma.FieldRef<"IngestionCursor", 'String'>
  readonly updatedAt: Prisma.FieldRef<"IngestionCursor", 'DateTime'>
}
    

// Custom InputTypes
/**
 * IngestionCursor findUnique
 */
export type IngestionCursorFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the IngestionCursor
   */
  select?: Prisma.IngestionCursorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the IngestionCursor
   */
  omit?: Prisma.IngestionCursorOmit<ExtArgs> | null
  /**
   * Filter, which IngestionCursor to fetch.
   */
  where: Prisma.IngestionCursorWhereUniqueInput
}

/**
 * IngestionCursor findUniqueOrThrow
 */
export type IngestionCursorFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the IngestionCursor
   */
  select?: Prisma.IngestionCursorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the IngestionCursor
   */
  omit?: Prisma.IngestionCursorOmit<ExtArgs> | null
  /**
   * Filter, which IngestionCursor to fetch.
   */
  where: Prisma.IngestionCursorWhereUniqueInput
}

/**
 * IngestionCursor findFirst
 */
export type IngestionCursorFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the IngestionCursor
   */
  select?: Prisma.IngestionCursorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the IngestionCursor
   */
  omit?: Prisma.IngestionCursorOmit<ExtArgs> | null
  /**
   * Filter, which IngestionCursor to fetch.
   */
  where?: Prisma.IngestionCursorWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of IngestionCursors to fetch.
   */
  orderBy?: Prisma.IngestionCursorOrderByWithRelationInput | Prisma.IngestionCursorOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for IngestionCursors.
   */
  cursor?: Prisma.IngestionCursorWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` IngestionCursors from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` IngestionCursors.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of IngestionCursors.
   */
  distinct?: Prisma.IngestionCursorScalarFieldEnum | Prisma.IngestionCursorScalarFieldEnum[]
}

/**
 * IngestionCursor findFirstOrThrow
 */
export type IngestionCursorFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the IngestionCursor
   */
  select?: Prisma.IngestionCursorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the IngestionCursor
   */
  omit?: Prisma.IngestionCursorOmit<ExtArgs> | null
  /**
   * Filter, which IngestionCursor to fetch.
   */
  where?: Prisma.IngestionCursorWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of IngestionCursors to fetch.
   */
  orderBy?: Prisma.IngestionCursorOrderByWithRelationInput | Prisma.IngestionCursorOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for IngestionCursors.
   */
  cursor?: Prisma.IngestionCursorWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` IngestionCursors from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` IngestionCursors.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of IngestionCursors.
   */
  distinct?: Prisma.IngestionCursorScalarFieldEnum | Prisma.IngestionCursorScalarFieldEnum[]
}

/**
 * IngestionCursor findMany
 */
export type IngestionCursorFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the IngestionCursor
   */
  select?: Prisma.IngestionCursorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the IngestionCursor
   */
  omit?: Prisma.IngestionCursorOmit<ExtArgs> | null
  /**
   * Filter, which IngestionCursors to fetch.
   */
  where?: Prisma.IngestionCursorWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of IngestionCursors to fetch.
   */
  orderBy?: Prisma.IngestionCursorOrderByWithRelationInput | Prisma.IngestionCursorOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing IngestionCursors.
   */
  cursor?: Prisma.IngestionCursorWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` IngestionCursors from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` IngestionCursors.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of IngestionCursors.
   */
  distinct?: Prisma.IngestionCursorScalarFieldEnum | Prisma.IngestionCursorScalarFieldEnum[]
}

/**
 * IngestionCursor create
 */
export type IngestionCursorCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the IngestionCursor
   */
  select?: Prisma.IngestionCursorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the IngestionCursor
   */
  omit?: Prisma.IngestionCursorOmit<ExtArgs> | null
  /**
   * The data needed to create a IngestionCursor.
   */
  data: Prisma.XOR<Prisma.IngestionCursorCreateInput, Prisma.IngestionCursorUncheckedCreateInput>
}

/**
 * IngestionCursor createMany
 */
export type IngestionCursorCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many IngestionCursors.
   */
  data: Prisma.IngestionCursorCreateManyInput | Prisma.IngestionCursorCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * IngestionCursor createManyAndReturn
 */
export type IngestionCursorCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the IngestionCursor
   */
  select?: Prisma.IngestionCursorSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the IngestionCursor
   */
  omit?: Prisma.IngestionCursorOmit<ExtArgs> | null
  /**
   * The data used to create many IngestionCursors.
   */
  data: Prisma.IngestionCursorCreateManyInput | Prisma.IngestionCursorCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * IngestionCursor update
 */
export type IngestionCursorUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the IngestionCursor
   */
  select?: Prisma.IngestionCursorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the IngestionCursor
   */
  omit?: Prisma.IngestionCursorOmit<ExtArgs> | null
  /**
   * The data needed to update a IngestionCursor.
   */
  data: Prisma.XOR<Prisma.IngestionCursorUpdateInput, Prisma.IngestionCursorUncheckedUpdateInput>
  /**
   * Choose, which IngestionCursor to update.
   */
  where: Prisma.IngestionCursorWhereUniqueInput
}

/**
 * IngestionCursor updateMany
 */
export type IngestionCursorUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update IngestionCursors.
   */
  data: Prisma.XOR<Prisma.IngestionCursorUpdateManyMutationInput, Prisma.IngestionCursorUncheckedUpdateManyInput>
  /**
   * Filter which IngestionCursors to update
   */
  where?: Prisma.IngestionCursorWhereInput
  /**
   * Limit how many IngestionCursors to update.
   */
  limit?: number
}

/**
 * IngestionCursor updateManyAndReturn
 */
export type IngestionCursorUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the IngestionCursor
   */
  select?: Prisma.IngestionCursorSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the IngestionCursor
   */
  omit?: Prisma.IngestionCursorOmit<ExtArgs> | null
  /**
   * The data used to update IngestionCursors.
   */
  data: Prisma.XOR<Prisma.IngestionCursorUpdateManyMutationInput, Prisma.IngestionCursorUncheckedUpdateManyInput>
  /**
   * Filter which IngestionCursors to update
   */
  where?: Prisma.IngestionCursorWhereInput
  /**
   * Limit how many IngestionCursors to update.
   */
  limit?: number
}

/**
 * IngestionCursor upsert
 */
export type IngestionCursorUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the IngestionCursor
   */
  select?: Prisma.IngestionCursorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the IngestionCursor
   */
  omit?: Prisma.IngestionCursorOmit<ExtArgs> | null
  /**
   * The filter to search for the IngestionCursor to update in case it exists.
   */
  where: Prisma.IngestionCursorWhereUniqueInput
  /**
   * In case the IngestionCursor found by the `where` argument doesn't exist, create a new IngestionCursor with this data.
   */
  create: Prisma.XOR<Prisma.IngestionCursorCreateInput, Prisma.IngestionCursorUncheckedCreateInput>
  /**
   * In case the IngestionCursor was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.IngestionCursorUpdateInput, Prisma.IngestionCursorUncheckedUpdateInput>
}

/**
 * IngestionCursor delete
 */
export type IngestionCursorDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the IngestionCursor
   */
  select?: Prisma.IngestionCursorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the IngestionCursor
   */
  omit?: Prisma.IngestionCursorOmit<ExtArgs> | null
  /**
   * Filter which IngestionCursor to delete.
   */
  where: Prisma.IngestionCursorWhereUniqueInput
}

/**
 * IngestionCursor deleteMany
 */
export type IngestionCursorDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which IngestionCursors to delete
   */
  where?: Prisma.IngestionCursorWhereInput
  /**
   * Limit how many IngestionCursors to delete.
   */
  limit?: number
}

/**
 * IngestionCursor without action
 */
export type IngestionCursorDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the IngestionCursor
   */
  select?: Prisma.IngestionCursorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the IngestionCursor
   */
  omit?: Prisma.IngestionCursorOmit<ExtArgs> | null
}
