
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `MarketPrice` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model MarketPrice
 * 
 */
export type MarketPriceModel = runtime.Types.Result.DefaultSelection<Prisma.$MarketPricePayload>

export type AggregateMarketPrice = {
  _count: MarketPriceCountAggregateOutputType | null
  _avg: MarketPriceAvgAggregateOutputType | null
  _sum: MarketPriceSumAggregateOutputType | null
  _min: MarketPriceMinAggregateOutputType | null
  _max: MarketPriceMaxAggregateOutputType | null
}

export type MarketPriceAvgAggregateOutputType = {
  id: number | null
  outcomeIndex: number | null
  price: runtime.Decimal | null
}

export type MarketPriceSumAggregateOutputType = {
  id: bigint | null
  outcomeIndex: number | null
  price: runtime.Decimal | null
}

export type MarketPriceMinAggregateOutputType = {
  id: bigint | null
  conditionId: string | null
  outcomeIndex: number | null
  price: runtime.Decimal | null
  capturedAt: Date | null
}

export type MarketPriceMaxAggregateOutputType = {
  id: bigint | null
  conditionId: string | null
  outcomeIndex: number | null
  price: runtime.Decimal | null
  capturedAt: Date | null
}

export type MarketPriceCountAggregateOutputType = {
  id: number
  conditionId: number
  outcomeIndex: number
  price: number
  capturedAt: number
  _all: number
}


export type MarketPriceAvgAggregateInputType = {
  id?: true
  outcomeIndex?: true
  price?: true
}

export type MarketPriceSumAggregateInputType = {
  id?: true
  outcomeIndex?: true
  price?: true
}

export type MarketPriceMinAggregateInputType = {
  id?: true
  conditionId?: true
  outcomeIndex?: true
  price?: true
  capturedAt?: true
}

export type MarketPriceMaxAggregateInputType = {
  id?: true
  conditionId?: true
  outcomeIndex?: true
  price?: true
  capturedAt?: true
}

export type MarketPriceCountAggregateInputType = {
  id?: true
  conditionId?: true
  outcomeIndex?: true
  price?: true
  capturedAt?: true
  _all?: true
}

export type MarketPriceAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which MarketPrice to aggregate.
   */
  where?: Prisma.MarketPriceWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MarketPrices to fetch.
   */
  orderBy?: Prisma.MarketPriceOrderByWithRelationInput | Prisma.MarketPriceOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.MarketPriceWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MarketPrices from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MarketPrices.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned MarketPrices
  **/
  _count?: true | MarketPriceCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: MarketPriceAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: MarketPriceSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: MarketPriceMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: MarketPriceMaxAggregateInputType
}

export type GetMarketPriceAggregateType<T extends MarketPriceAggregateArgs> = {
      [P in keyof T & keyof AggregateMarketPrice]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateMarketPrice[P]>
    : Prisma.GetScalarType<T[P], AggregateMarketPrice[P]>
}




export type MarketPriceGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.MarketPriceWhereInput
  orderBy?: Prisma.MarketPriceOrderByWithAggregationInput | Prisma.MarketPriceOrderByWithAggregationInput[]
  by: Prisma.MarketPriceScalarFieldEnum[] | Prisma.MarketPriceScalarFieldEnum
  having?: Prisma.MarketPriceScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: MarketPriceCountAggregateInputType | true
  _avg?: MarketPriceAvgAggregateInputType
  _sum?: MarketPriceSumAggregateInputType
  _min?: MarketPriceMinAggregateInputType
  _max?: MarketPriceMaxAggregateInputType
}

export type MarketPriceGroupByOutputType = {
  id: bigint
  conditionId: string
  outcomeIndex: number
  price: runtime.Decimal
  capturedAt: Date
  _count: MarketPriceCountAggregateOutputType | null
  _avg: MarketPriceAvgAggregateOutputType | null
  _sum: MarketPriceSumAggregateOutputType | null
  _min: MarketPriceMinAggregateOutputType | null
  _max: MarketPriceMaxAggregateOutputType | null
}

type GetMarketPriceGroupByPayload<T extends MarketPriceGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<MarketPriceGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof MarketPriceGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], MarketPriceGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], MarketPriceGroupByOutputType[P]>
      }
    >
  >



export type MarketPriceWhereInput = {
  AND?: Prisma.MarketPriceWhereInput | Prisma.MarketPriceWhereInput[]
  OR?: Prisma.MarketPriceWhereInput[]
  NOT?: Prisma.MarketPriceWhereInput | Prisma.MarketPriceWhereInput[]
  id?: Prisma.BigIntFilter<"MarketPrice"> | bigint | number
  conditionId?: Prisma.StringFilter<"MarketPrice"> | string
  outcomeIndex?: Prisma.IntFilter<"MarketPrice"> | number
  price?: Prisma.DecimalFilter<"MarketPrice"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  capturedAt?: Prisma.DateTimeFilter<"MarketPrice"> | Date | string
  market?: Prisma.XOR<Prisma.MarketScalarRelationFilter, Prisma.MarketWhereInput>
}

export type MarketPriceOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  conditionId?: Prisma.SortOrder
  outcomeIndex?: Prisma.SortOrder
  price?: Prisma.SortOrder
  capturedAt?: Prisma.SortOrder
  market?: Prisma.MarketOrderByWithRelationInput
}

export type MarketPriceWhereUniqueInput = Prisma.AtLeast<{
  id?: bigint | number
  AND?: Prisma.MarketPriceWhereInput | Prisma.MarketPriceWhereInput[]
  OR?: Prisma.MarketPriceWhereInput[]
  NOT?: Prisma.MarketPriceWhereInput | Prisma.MarketPriceWhereInput[]
  conditionId?: Prisma.StringFilter<"MarketPrice"> | string
  outcomeIndex?: Prisma.IntFilter<"MarketPrice"> | number
  price?: Prisma.DecimalFilter<"MarketPrice"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  capturedAt?: Prisma.DateTimeFilter<"MarketPrice"> | Date | string
  market?: Prisma.XOR<Prisma.MarketScalarRelationFilter, Prisma.MarketWhereInput>
}, "id">

export type MarketPriceOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  conditionId?: Prisma.SortOrder
  outcomeIndex?: Prisma.SortOrder
  price?: Prisma.SortOrder
  capturedAt?: Prisma.SortOrder
  _count?: Prisma.MarketPriceCountOrderByAggregateInput
  _avg?: Prisma.MarketPriceAvgOrderByAggregateInput
  _max?: Prisma.MarketPriceMaxOrderByAggregateInput
  _min?: Prisma.MarketPriceMinOrderByAggregateInput
  _sum?: Prisma.MarketPriceSumOrderByAggregateInput
}

export type MarketPriceScalarWhereWithAggregatesInput = {
  AND?: Prisma.MarketPriceScalarWhereWithAggregatesInput | Prisma.MarketPriceScalarWhereWithAggregatesInput[]
  OR?: Prisma.MarketPriceScalarWhereWithAggregatesInput[]
  NOT?: Prisma.MarketPriceScalarWhereWithAggregatesInput | Prisma.MarketPriceScalarWhereWithAggregatesInput[]
  id?: Prisma.BigIntWithAggregatesFilter<"MarketPrice"> | bigint | number
  conditionId?: Prisma.StringWithAggregatesFilter<"MarketPrice"> | string
  outcomeIndex?: Prisma.IntWithAggregatesFilter<"MarketPrice"> | number
  price?: Prisma.DecimalWithAggregatesFilter<"MarketPrice"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  capturedAt?: Prisma.DateTimeWithAggregatesFilter<"MarketPrice"> | Date | string
}

export type MarketPriceCreateInput = {
  id?: bigint | number
  outcomeIndex: number
  price: runtime.Decimal | runtime.DecimalJsLike | number | string
  capturedAt: Date | string
  market: Prisma.MarketCreateNestedOneWithoutPricesInput
}

export type MarketPriceUncheckedCreateInput = {
  id?: bigint | number
  conditionId: string
  outcomeIndex: number
  price: runtime.Decimal | runtime.DecimalJsLike | number | string
  capturedAt: Date | string
}

export type MarketPriceUpdateInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  outcomeIndex?: Prisma.IntFieldUpdateOperationsInput | number
  price?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  capturedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  market?: Prisma.MarketUpdateOneRequiredWithoutPricesNestedInput
}

export type MarketPriceUncheckedUpdateInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  conditionId?: Prisma.StringFieldUpdateOperationsInput | string
  outcomeIndex?: Prisma.IntFieldUpdateOperationsInput | number
  price?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  capturedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MarketPriceCreateManyInput = {
  id?: bigint | number
  conditionId: string
  outcomeIndex: number
  price: runtime.Decimal | runtime.DecimalJsLike | number | string
  capturedAt: Date | string
}

export type MarketPriceUpdateManyMutationInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  outcomeIndex?: Prisma.IntFieldUpdateOperationsInput | number
  price?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  capturedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MarketPriceUncheckedUpdateManyInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  conditionId?: Prisma.StringFieldUpdateOperationsInput | string
  outcomeIndex?: Prisma.IntFieldUpdateOperationsInput | number
  price?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  capturedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MarketPriceListRelationFilter = {
  every?: Prisma.MarketPriceWhereInput
  some?: Prisma.MarketPriceWhereInput
  none?: Prisma.MarketPriceWhereInput
}

export type MarketPriceOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type MarketPriceCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  conditionId?: Prisma.SortOrder
  outcomeIndex?: Prisma.SortOrder
  price?: Prisma.SortOrder
  capturedAt?: Prisma.SortOrder
}

export type MarketPriceAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  outcomeIndex?: Prisma.SortOrder
  price?: Prisma.SortOrder
}

export type MarketPriceMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  conditionId?: Prisma.SortOrder
  outcomeIndex?: Prisma.SortOrder
  price?: Prisma.SortOrder
  capturedAt?: Prisma.SortOrder
}

export type MarketPriceMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  conditionId?: Prisma.SortOrder
  outcomeIndex?: Prisma.SortOrder
  price?: Prisma.SortOrder
  capturedAt?: Prisma.SortOrder
}

export type MarketPriceSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  outcomeIndex?: Prisma.SortOrder
  price?: Prisma.SortOrder
}

export type MarketPriceCreateNestedManyWithoutMarketInput = {
  create?: Prisma.XOR<Prisma.MarketPriceCreateWithoutMarketInput, Prisma.MarketPriceUncheckedCreateWithoutMarketInput> | Prisma.MarketPriceCreateWithoutMarketInput[] | Prisma.MarketPriceUncheckedCreateWithoutMarketInput[]
  connectOrCreate?: Prisma.MarketPriceCreateOrConnectWithoutMarketInput | Prisma.MarketPriceCreateOrConnectWithoutMarketInput[]
  createMany?: Prisma.MarketPriceCreateManyMarketInputEnvelope
  connect?: Prisma.MarketPriceWhereUniqueInput | Prisma.MarketPriceWhereUniqueInput[]
}

export type MarketPriceUncheckedCreateNestedManyWithoutMarketInput = {
  create?: Prisma.XOR<Prisma.MarketPriceCreateWithoutMarketInput, Prisma.MarketPriceUncheckedCreateWithoutMarketInput> | Prisma.MarketPriceCreateWithoutMarketInput[] | Prisma.MarketPriceUncheckedCreateWithoutMarketInput[]
  connectOrCreate?: Prisma.MarketPriceCreateOrConnectWithoutMarketInput | Prisma.MarketPriceCreateOrConnectWithoutMarketInput[]
  createMany?: Prisma.MarketPriceCreateManyMarketInputEnvelope
  connect?: Prisma.MarketPriceWhereUniqueInput | Prisma.MarketPriceWhereUniqueInput[]
}

export type MarketPriceUpdateManyWithoutMarketNestedInput = {
  create?: Prisma.XOR<Prisma.MarketPriceCreateWithoutMarketInput, Prisma.MarketPriceUncheckedCreateWithoutMarketInput> | Prisma.MarketPriceCreateWithoutMarketInput[] | Prisma.MarketPriceUncheckedCreateWithoutMarketInput[]
  connectOrCreate?: Prisma.MarketPriceCreateOrConnectWithoutMarketInput | Prisma.MarketPriceCreateOrConnectWithoutMarketInput[]
  upsert?: Prisma.MarketPriceUpsertWithWhereUniqueWithoutMarketInput | Prisma.MarketPriceUpsertWithWhereUniqueWithoutMarketInput[]
  createMany?: Prisma.MarketPriceCreateManyMarketInputEnvelope
  set?: Prisma.MarketPriceWhereUniqueInput | Prisma.MarketPriceWhereUniqueInput[]
  disconnect?: Prisma.MarketPriceWhereUniqueInput | Prisma.MarketPriceWhereUniqueInput[]
  delete?: Prisma.MarketPriceWhereUniqueInput | Prisma.MarketPriceWhereUniqueInput[]
  connect?: Prisma.MarketPriceWhereUniqueInput | Prisma.MarketPriceWhereUniqueInput[]
  update?: Prisma.MarketPriceUpdateWithWhereUniqueWithoutMarketInput | Prisma.MarketPriceUpdateWithWhereUniqueWithoutMarketInput[]
  updateMany?: Prisma.MarketPriceUpdateManyWithWhereWithoutMarketInput | Prisma.MarketPriceUpdateManyWithWhereWithoutMarketInput[]
  deleteMany?: Prisma.MarketPriceScalarWhereInput | Prisma.MarketPriceScalarWhereInput[]
}

export type MarketPriceUncheckedUpdateManyWithoutMarketNestedInput = {
  create?: Prisma.XOR<Prisma.MarketPriceCreateWithoutMarketInput, Prisma.MarketPriceUncheckedCreateWithoutMarketInput> | Prisma.MarketPriceCreateWithoutMarketInput[] | Prisma.MarketPriceUncheckedCreateWithoutMarketInput[]
  connectOrCreate?: Prisma.MarketPriceCreateOrConnectWithoutMarketInput | Prisma.MarketPriceCreateOrConnectWithoutMarketInput[]
  upsert?: Prisma.MarketPriceUpsertWithWhereUniqueWithoutMarketInput | Prisma.MarketPriceUpsertWithWhereUniqueWithoutMarketInput[]
  createMany?: Prisma.MarketPriceCreateManyMarketInputEnvelope
  set?: Prisma.MarketPriceWhereUniqueInput | Prisma.MarketPriceWhereUniqueInput[]
  disconnect?: Prisma.MarketPriceWhereUniqueInput | Prisma.MarketPriceWhereUniqueInput[]
  delete?: Prisma.MarketPriceWhereUniqueInput | Prisma.MarketPriceWhereUniqueInput[]
  connect?: Prisma.MarketPriceWhereUniqueInput | Prisma.MarketPriceWhereUniqueInput[]
  update?: Prisma.MarketPriceUpdateWithWhereUniqueWithoutMarketInput | Prisma.MarketPriceUpdateWithWhereUniqueWithoutMarketInput[]
  updateMany?: Prisma.MarketPriceUpdateManyWithWhereWithoutMarketInput | Prisma.MarketPriceUpdateManyWithWhereWithoutMarketInput[]
  deleteMany?: Prisma.MarketPriceScalarWhereInput | Prisma.MarketPriceScalarWhereInput[]
}

export type BigIntFieldUpdateOperationsInput = {
  set?: bigint | number
  increment?: bigint | number
  decrement?: bigint | number
  multiply?: bigint | number
  divide?: bigint | number
}

export type MarketPriceCreateWithoutMarketInput = {
  id?: bigint | number
  outcomeIndex: number
  price: runtime.Decimal | runtime.DecimalJsLike | number | string
  capturedAt: Date | string
}

export type MarketPriceUncheckedCreateWithoutMarketInput = {
  id?: bigint | number
  outcomeIndex: number
  price: runtime.Decimal | runtime.DecimalJsLike | number | string
  capturedAt: Date | string
}

export type MarketPriceCreateOrConnectWithoutMarketInput = {
  where: Prisma.MarketPriceWhereUniqueInput
  create: Prisma.XOR<Prisma.MarketPriceCreateWithoutMarketInput, Prisma.MarketPriceUncheckedCreateWithoutMarketInput>
}

export type MarketPriceCreateManyMarketInputEnvelope = {
  data: Prisma.MarketPriceCreateManyMarketInput | Prisma.MarketPriceCreateManyMarketInput[]
  skipDuplicates?: boolean
}

export type MarketPriceUpsertWithWhereUniqueWithoutMarketInput = {
  where: Prisma.MarketPriceWhereUniqueInput
  update: Prisma.XOR<Prisma.MarketPriceUpdateWithoutMarketInput, Prisma.MarketPriceUncheckedUpdateWithoutMarketInput>
  create: Prisma.XOR<Prisma.MarketPriceCreateWithoutMarketInput, Prisma.MarketPriceUncheckedCreateWithoutMarketInput>
}

export type MarketPriceUpdateWithWhereUniqueWithoutMarketInput = {
  where: Prisma.MarketPriceWhereUniqueInput
  data: Prisma.XOR<Prisma.MarketPriceUpdateWithoutMarketInput, Prisma.MarketPriceUncheckedUpdateWithoutMarketInput>
}

export type MarketPriceUpdateManyWithWhereWithoutMarketInput = {
  where: Prisma.MarketPriceScalarWhereInput
  data: Prisma.XOR<Prisma.MarketPriceUpdateManyMutationInput, Prisma.MarketPriceUncheckedUpdateManyWithoutMarketInput>
}

export type MarketPriceScalarWhereInput = {
  AND?: Prisma.MarketPriceScalarWhereInput | Prisma.MarketPriceScalarWhereInput[]
  OR?: Prisma.MarketPriceScalarWhereInput[]
  NOT?: Prisma.MarketPriceScalarWhereInput | Prisma.MarketPriceScalarWhereInput[]
  id?: Prisma.BigIntFilter<"MarketPrice"> | bigint | number
  conditionId?: Prisma.StringFilter<"MarketPrice"> | string
  outcomeIndex?: Prisma.IntFilter<"MarketPrice"> | number
  price?: Prisma.DecimalFilter<"MarketPrice"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  capturedAt?: Prisma.DateTimeFilter<"MarketPrice"> | Date | string
}

export type MarketPriceCreateManyMarketInput = {
  id?: bigint | number
  outcomeIndex: number
  price: runtime.Decimal | runtime.DecimalJsLike | number | string
  capturedAt: Date | string
}

export type MarketPriceUpdateWithoutMarketInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  outcomeIndex?: Prisma.IntFieldUpdateOperationsInput | number
  price?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  capturedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MarketPriceUncheckedUpdateWithoutMarketInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  outcomeIndex?: Prisma.IntFieldUpdateOperationsInput | number
  price?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  capturedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MarketPriceUncheckedUpdateManyWithoutMarketInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  outcomeIndex?: Prisma.IntFieldUpdateOperationsInput | number
  price?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  capturedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type MarketPriceSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  conditionId?: boolean
  outcomeIndex?: boolean
  price?: boolean
  capturedAt?: boolean
  market?: boolean | Prisma.MarketDefaultArgs<ExtArgs>
}, ExtArgs["result"]["marketPrice"]>

export type MarketPriceSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  conditionId?: boolean
  outcomeIndex?: boolean
  price?: boolean
  capturedAt?: boolean
  market?: boolean | Prisma.MarketDefaultArgs<ExtArgs>
}, ExtArgs["result"]["marketPrice"]>

export type MarketPriceSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  conditionId?: boolean
  outcomeIndex?: boolean
  price?: boolean
  capturedAt?: boolean
  market?: boolean | Prisma.MarketDefaultArgs<ExtArgs>
}, ExtArgs["result"]["marketPrice"]>

export type MarketPriceSelectScalar = {
  id?: boolean
  conditionId?: boolean
  outcomeIndex?: boolean
  price?: boolean
  capturedAt?: boolean
}

export type MarketPriceOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "conditionId" | "outcomeIndex" | "price" | "capturedAt", ExtArgs["result"]["marketPrice"]>
export type MarketPriceInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  market?: boolean | Prisma.MarketDefaultArgs<ExtArgs>
}
export type MarketPriceIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  market?: boolean | Prisma.MarketDefaultArgs<ExtArgs>
}
export type MarketPriceIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  market?: boolean | Prisma.MarketDefaultArgs<ExtArgs>
}

export type $MarketPricePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "MarketPrice"
  objects: {
    market: Prisma.$MarketPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: bigint
    conditionId: string
    outcomeIndex: number
    price: runtime.Decimal
    capturedAt: Date
  }, ExtArgs["result"]["marketPrice"]>
  composites: {}
}

export type MarketPriceGetPayload<S extends boolean | null | undefined | MarketPriceDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$MarketPricePayload, S>

export type MarketPriceCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<MarketPriceFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: MarketPriceCountAggregateInputType | true
  }

export interface MarketPriceDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['MarketPrice'], meta: { name: 'MarketPrice' } }
  /**
   * Find zero or one MarketPrice that matches the filter.
   * @param {MarketPriceFindUniqueArgs} args - Arguments to find a MarketPrice
   * @example
   * // Get one MarketPrice
   * const marketPrice = await prisma.marketPrice.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends MarketPriceFindUniqueArgs>(args: Prisma.SelectSubset<T, MarketPriceFindUniqueArgs<ExtArgs>>): Prisma.Prisma__MarketPriceClient<runtime.Types.Result.GetResult<Prisma.$MarketPricePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one MarketPrice that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {MarketPriceFindUniqueOrThrowArgs} args - Arguments to find a MarketPrice
   * @example
   * // Get one MarketPrice
   * const marketPrice = await prisma.marketPrice.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends MarketPriceFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, MarketPriceFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__MarketPriceClient<runtime.Types.Result.GetResult<Prisma.$MarketPricePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first MarketPrice that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MarketPriceFindFirstArgs} args - Arguments to find a MarketPrice
   * @example
   * // Get one MarketPrice
   * const marketPrice = await prisma.marketPrice.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends MarketPriceFindFirstArgs>(args?: Prisma.SelectSubset<T, MarketPriceFindFirstArgs<ExtArgs>>): Prisma.Prisma__MarketPriceClient<runtime.Types.Result.GetResult<Prisma.$MarketPricePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first MarketPrice that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MarketPriceFindFirstOrThrowArgs} args - Arguments to find a MarketPrice
   * @example
   * // Get one MarketPrice
   * const marketPrice = await prisma.marketPrice.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends MarketPriceFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, MarketPriceFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__MarketPriceClient<runtime.Types.Result.GetResult<Prisma.$MarketPricePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more MarketPrices that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MarketPriceFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all MarketPrices
   * const marketPrices = await prisma.marketPrice.findMany()
   * 
   * // Get first 10 MarketPrices
   * const marketPrices = await prisma.marketPrice.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const marketPriceWithIdOnly = await prisma.marketPrice.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends MarketPriceFindManyArgs>(args?: Prisma.SelectSubset<T, MarketPriceFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MarketPricePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a MarketPrice.
   * @param {MarketPriceCreateArgs} args - Arguments to create a MarketPrice.
   * @example
   * // Create one MarketPrice
   * const MarketPrice = await prisma.marketPrice.create({
   *   data: {
   *     // ... data to create a MarketPrice
   *   }
   * })
   * 
   */
  create<T extends MarketPriceCreateArgs>(args: Prisma.SelectSubset<T, MarketPriceCreateArgs<ExtArgs>>): Prisma.Prisma__MarketPriceClient<runtime.Types.Result.GetResult<Prisma.$MarketPricePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many MarketPrices.
   * @param {MarketPriceCreateManyArgs} args - Arguments to create many MarketPrices.
   * @example
   * // Create many MarketPrices
   * const marketPrice = await prisma.marketPrice.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends MarketPriceCreateManyArgs>(args?: Prisma.SelectSubset<T, MarketPriceCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many MarketPrices and returns the data saved in the database.
   * @param {MarketPriceCreateManyAndReturnArgs} args - Arguments to create many MarketPrices.
   * @example
   * // Create many MarketPrices
   * const marketPrice = await prisma.marketPrice.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many MarketPrices and only return the `id`
   * const marketPriceWithIdOnly = await prisma.marketPrice.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends MarketPriceCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, MarketPriceCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MarketPricePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a MarketPrice.
   * @param {MarketPriceDeleteArgs} args - Arguments to delete one MarketPrice.
   * @example
   * // Delete one MarketPrice
   * const MarketPrice = await prisma.marketPrice.delete({
   *   where: {
   *     // ... filter to delete one MarketPrice
   *   }
   * })
   * 
   */
  delete<T extends MarketPriceDeleteArgs>(args: Prisma.SelectSubset<T, MarketPriceDeleteArgs<ExtArgs>>): Prisma.Prisma__MarketPriceClient<runtime.Types.Result.GetResult<Prisma.$MarketPricePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one MarketPrice.
   * @param {MarketPriceUpdateArgs} args - Arguments to update one MarketPrice.
   * @example
   * // Update one MarketPrice
   * const marketPrice = await prisma.marketPrice.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends MarketPriceUpdateArgs>(args: Prisma.SelectSubset<T, MarketPriceUpdateArgs<ExtArgs>>): Prisma.Prisma__MarketPriceClient<runtime.Types.Result.GetResult<Prisma.$MarketPricePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more MarketPrices.
   * @param {MarketPriceDeleteManyArgs} args - Arguments to filter MarketPrices to delete.
   * @example
   * // Delete a few MarketPrices
   * const { count } = await prisma.marketPrice.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends MarketPriceDeleteManyArgs>(args?: Prisma.SelectSubset<T, MarketPriceDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more MarketPrices.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MarketPriceUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many MarketPrices
   * const marketPrice = await prisma.marketPrice.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends MarketPriceUpdateManyArgs>(args: Prisma.SelectSubset<T, MarketPriceUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more MarketPrices and returns the data updated in the database.
   * @param {MarketPriceUpdateManyAndReturnArgs} args - Arguments to update many MarketPrices.
   * @example
   * // Update many MarketPrices
   * const marketPrice = await prisma.marketPrice.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more MarketPrices and only return the `id`
   * const marketPriceWithIdOnly = await prisma.marketPrice.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends MarketPriceUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, MarketPriceUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MarketPricePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one MarketPrice.
   * @param {MarketPriceUpsertArgs} args - Arguments to update or create a MarketPrice.
   * @example
   * // Update or create a MarketPrice
   * const marketPrice = await prisma.marketPrice.upsert({
   *   create: {
   *     // ... data to create a MarketPrice
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the MarketPrice we want to update
   *   }
   * })
   */
  upsert<T extends MarketPriceUpsertArgs>(args: Prisma.SelectSubset<T, MarketPriceUpsertArgs<ExtArgs>>): Prisma.Prisma__MarketPriceClient<runtime.Types.Result.GetResult<Prisma.$MarketPricePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of MarketPrices.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MarketPriceCountArgs} args - Arguments to filter MarketPrices to count.
   * @example
   * // Count the number of MarketPrices
   * const count = await prisma.marketPrice.count({
   *   where: {
   *     // ... the filter for the MarketPrices we want to count
   *   }
   * })
  **/
  count<T extends MarketPriceCountArgs>(
    args?: Prisma.Subset<T, MarketPriceCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], MarketPriceCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a MarketPrice.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MarketPriceAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends MarketPriceAggregateArgs>(args: Prisma.Subset<T, MarketPriceAggregateArgs>): Prisma.PrismaPromise<GetMarketPriceAggregateType<T>>

  /**
   * Group by MarketPrice.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MarketPriceGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends MarketPriceGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: MarketPriceGroupByArgs['orderBy'] }
      : { orderBy?: MarketPriceGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, MarketPriceGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetMarketPriceGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the MarketPrice model
 */
readonly fields: MarketPriceFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for MarketPrice.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__MarketPriceClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  market<T extends Prisma.MarketDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.MarketDefaultArgs<ExtArgs>>): Prisma.Prisma__MarketClient<runtime.Types.Result.GetResult<Prisma.$MarketPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the MarketPrice model
 */
export interface MarketPriceFieldRefs {
  readonly id: Prisma.FieldRef<"MarketPrice", 'BigInt'>
  readonly conditionId: Prisma.FieldRef<"MarketPrice", 'String'>
  readonly outcomeIndex: Prisma.FieldRef<"MarketPrice", 'Int'>
  readonly price: Prisma.FieldRef<"MarketPrice", 'Decimal'>
  readonly capturedAt: Prisma.FieldRef<"MarketPrice", 'DateTime'>
}
    

// Custom InputTypes
/**
 * MarketPrice findUnique
 */
export type MarketPriceFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MarketPrice
   */
  select?: Prisma.MarketPriceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MarketPrice
   */
  omit?: Prisma.MarketPriceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MarketPriceInclude<ExtArgs> | null
  /**
   * Filter, which MarketPrice to fetch.
   */
  where: Prisma.MarketPriceWhereUniqueInput
}

/**
 * MarketPrice findUniqueOrThrow
 */
export type MarketPriceFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MarketPrice
   */
  select?: Prisma.MarketPriceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MarketPrice
   */
  omit?: Prisma.MarketPriceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MarketPriceInclude<ExtArgs> | null
  /**
   * Filter, which MarketPrice to fetch.
   */
  where: Prisma.MarketPriceWhereUniqueInput
}

/**
 * MarketPrice findFirst
 */
export type MarketPriceFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MarketPrice
   */
  select?: Prisma.MarketPriceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MarketPrice
   */
  omit?: Prisma.MarketPriceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MarketPriceInclude<ExtArgs> | null
  /**
   * Filter, which MarketPrice to fetch.
   */
  where?: Prisma.MarketPriceWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MarketPrices to fetch.
   */
  orderBy?: Prisma.MarketPriceOrderByWithRelationInput | Prisma.MarketPriceOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for MarketPrices.
   */
  cursor?: Prisma.MarketPriceWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MarketPrices from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MarketPrices.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of MarketPrices.
   */
  distinct?: Prisma.MarketPriceScalarFieldEnum | Prisma.MarketPriceScalarFieldEnum[]
}

/**
 * MarketPrice findFirstOrThrow
 */
export type MarketPriceFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MarketPrice
   */
  select?: Prisma.MarketPriceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MarketPrice
   */
  omit?: Prisma.MarketPriceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MarketPriceInclude<ExtArgs> | null
  /**
   * Filter, which MarketPrice to fetch.
   */
  where?: Prisma.MarketPriceWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MarketPrices to fetch.
   */
  orderBy?: Prisma.MarketPriceOrderByWithRelationInput | Prisma.MarketPriceOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for MarketPrices.
   */
  cursor?: Prisma.MarketPriceWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MarketPrices from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MarketPrices.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of MarketPrices.
   */
  distinct?: Prisma.MarketPriceScalarFieldEnum | Prisma.MarketPriceScalarFieldEnum[]
}

/**
 * MarketPrice findMany
 */
export type MarketPriceFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MarketPrice
   */
  select?: Prisma.MarketPriceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MarketPrice
   */
  omit?: Prisma.MarketPriceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MarketPriceInclude<ExtArgs> | null
  /**
   * Filter, which MarketPrices to fetch.
   */
  where?: Prisma.MarketPriceWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MarketPrices to fetch.
   */
  orderBy?: Prisma.MarketPriceOrderByWithRelationInput | Prisma.MarketPriceOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing MarketPrices.
   */
  cursor?: Prisma.MarketPriceWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MarketPrices from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MarketPrices.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of MarketPrices.
   */
  distinct?: Prisma.MarketPriceScalarFieldEnum | Prisma.MarketPriceScalarFieldEnum[]
}

/**
 * MarketPrice create
 */
export type MarketPriceCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MarketPrice
   */
  select?: Prisma.MarketPriceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MarketPrice
   */
  omit?: Prisma.MarketPriceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MarketPriceInclude<ExtArgs> | null
  /**
   * The data needed to create a MarketPrice.
   */
  data: Prisma.XOR<Prisma.MarketPriceCreateInput, Prisma.MarketPriceUncheckedCreateInput>
}

/**
 * MarketPrice createMany
 */
export type MarketPriceCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many MarketPrices.
   */
  data: Prisma.MarketPriceCreateManyInput | Prisma.MarketPriceCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * MarketPrice createManyAndReturn
 */
export type MarketPriceCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MarketPrice
   */
  select?: Prisma.MarketPriceSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the MarketPrice
   */
  omit?: Prisma.MarketPriceOmit<ExtArgs> | null
  /**
   * The data used to create many MarketPrices.
   */
  data: Prisma.MarketPriceCreateManyInput | Prisma.MarketPriceCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MarketPriceIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * MarketPrice update
 */
export type MarketPriceUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MarketPrice
   */
  select?: Prisma.MarketPriceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MarketPrice
   */
  omit?: Prisma.MarketPriceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MarketPriceInclude<ExtArgs> | null
  /**
   * The data needed to update a MarketPrice.
   */
  data: Prisma.XOR<Prisma.MarketPriceUpdateInput, Prisma.MarketPriceUncheckedUpdateInput>
  /**
   * Choose, which MarketPrice to update.
   */
  where: Prisma.MarketPriceWhereUniqueInput
}

/**
 * MarketPrice updateMany
 */
export type MarketPriceUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update MarketPrices.
   */
  data: Prisma.XOR<Prisma.MarketPriceUpdateManyMutationInput, Prisma.MarketPriceUncheckedUpdateManyInput>
  /**
   * Filter which MarketPrices to update
   */
  where?: Prisma.MarketPriceWhereInput
  /**
   * Limit how many MarketPrices to update.
   */
  limit?: number
}

/**
 * MarketPrice updateManyAndReturn
 */
export type MarketPriceUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MarketPrice
   */
  select?: Prisma.MarketPriceSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the MarketPrice
   */
  omit?: Prisma.MarketPriceOmit<ExtArgs> | null
  /**
   * The data used to update MarketPrices.
   */
  data: Prisma.XOR<Prisma.MarketPriceUpdateManyMutationInput, Prisma.MarketPriceUncheckedUpdateManyInput>
  /**
   * Filter which MarketPrices to update
   */
  where?: Prisma.MarketPriceWhereInput
  /**
   * Limit how many MarketPrices to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MarketPriceIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * MarketPrice upsert
 */
export type MarketPriceUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MarketPrice
   */
  select?: Prisma.MarketPriceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MarketPrice
   */
  omit?: Prisma.MarketPriceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MarketPriceInclude<ExtArgs> | null
  /**
   * The filter to search for the MarketPrice to update in case it exists.
   */
  where: Prisma.MarketPriceWhereUniqueInput
  /**
   * In case the MarketPrice found by the `where` argument doesn't exist, create a new MarketPrice with this data.
   */
  create: Prisma.XOR<Prisma.MarketPriceCreateInput, Prisma.MarketPriceUncheckedCreateInput>
  /**
   * In case the MarketPrice was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.MarketPriceUpdateInput, Prisma.MarketPriceUncheckedUpdateInput>
}

/**
 * MarketPrice delete
 */
export type MarketPriceDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MarketPrice
   */
  select?: Prisma.MarketPriceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MarketPrice
   */
  omit?: Prisma.MarketPriceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MarketPriceInclude<ExtArgs> | null
  /**
   * Filter which MarketPrice to delete.
   */
  where: Prisma.MarketPriceWhereUniqueInput
}

/**
 * MarketPrice deleteMany
 */
export type MarketPriceDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which MarketPrices to delete
   */
  where?: Prisma.MarketPriceWhereInput
  /**
   * Limit how many MarketPrices to delete.
   */
  limit?: number
}

/**
 * MarketPrice without action
 */
export type MarketPriceDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MarketPrice
   */
  select?: Prisma.MarketPriceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MarketPrice
   */
  omit?: Prisma.MarketPriceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MarketPriceInclude<ExtArgs> | null
}
