
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `TraderStats` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model TraderStats
 * 
 */
export type TraderStatsModel = runtime.Types.Result.DefaultSelection<Prisma.$TraderStatsPayload>

export type AggregateTraderStats = {
  _count: TraderStatsCountAggregateOutputType | null
  _avg: TraderStatsAvgAggregateOutputType | null
  _sum: TraderStatsSumAggregateOutputType | null
  _min: TraderStatsMinAggregateOutputType | null
  _max: TraderStatsMaxAggregateOutputType | null
}

export type TraderStatsAvgAggregateOutputType = {
  tradeCount: number | null
  resolvedTrades: number | null
  winCount: number | null
  winRate: runtime.Decimal | null
  realisedPnl: runtime.Decimal | null
  roi: runtime.Decimal | null
  avgEdge: runtime.Decimal | null
  score: runtime.Decimal | null
}

export type TraderStatsSumAggregateOutputType = {
  tradeCount: number | null
  resolvedTrades: number | null
  winCount: number | null
  winRate: runtime.Decimal | null
  realisedPnl: runtime.Decimal | null
  roi: runtime.Decimal | null
  avgEdge: runtime.Decimal | null
  score: runtime.Decimal | null
}

export type TraderStatsMinAggregateOutputType = {
  wallet: string | null
  tradeCount: number | null
  resolvedTrades: number | null
  winCount: number | null
  winRate: runtime.Decimal | null
  realisedPnl: runtime.Decimal | null
  roi: runtime.Decimal | null
  avgEdge: runtime.Decimal | null
  score: runtime.Decimal | null
  firstTradeAt: Date | null
  lastTradeAt: Date | null
  updatedAt: Date | null
}

export type TraderStatsMaxAggregateOutputType = {
  wallet: string | null
  tradeCount: number | null
  resolvedTrades: number | null
  winCount: number | null
  winRate: runtime.Decimal | null
  realisedPnl: runtime.Decimal | null
  roi: runtime.Decimal | null
  avgEdge: runtime.Decimal | null
  score: runtime.Decimal | null
  firstTradeAt: Date | null
  lastTradeAt: Date | null
  updatedAt: Date | null
}

export type TraderStatsCountAggregateOutputType = {
  wallet: number
  tradeCount: number
  resolvedTrades: number
  winCount: number
  winRate: number
  realisedPnl: number
  roi: number
  avgEdge: number
  score: number
  firstTradeAt: number
  lastTradeAt: number
  updatedAt: number
  _all: number
}


export type TraderStatsAvgAggregateInputType = {
  tradeCount?: true
  resolvedTrades?: true
  winCount?: true
  winRate?: true
  realisedPnl?: true
  roi?: true
  avgEdge?: true
  score?: true
}

export type TraderStatsSumAggregateInputType = {
  tradeCount?: true
  resolvedTrades?: true
  winCount?: true
  winRate?: true
  realisedPnl?: true
  roi?: true
  avgEdge?: true
  score?: true
}

export type TraderStatsMinAggregateInputType = {
  wallet?: true
  tradeCount?: true
  resolvedTrades?: true
  winCount?: true
  winRate?: true
  realisedPnl?: true
  roi?: true
  avgEdge?: true
  score?: true
  firstTradeAt?: true
  lastTradeAt?: true
  updatedAt?: true
}

export type TraderStatsMaxAggregateInputType = {
  wallet?: true
  tradeCount?: true
  resolvedTrades?: true
  winCount?: true
  winRate?: true
  realisedPnl?: true
  roi?: true
  avgEdge?: true
  score?: true
  firstTradeAt?: true
  lastTradeAt?: true
  updatedAt?: true
}

export type TraderStatsCountAggregateInputType = {
  wallet?: true
  tradeCount?: true
  resolvedTrades?: true
  winCount?: true
  winRate?: true
  realisedPnl?: true
  roi?: true
  avgEdge?: true
  score?: true
  firstTradeAt?: true
  lastTradeAt?: true
  updatedAt?: true
  _all?: true
}

export type TraderStatsAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TraderStats to aggregate.
   */
  where?: Prisma.TraderStatsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TraderStats to fetch.
   */
  orderBy?: Prisma.TraderStatsOrderByWithRelationInput | Prisma.TraderStatsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.TraderStatsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TraderStats from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TraderStats.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned TraderStats
  **/
  _count?: true | TraderStatsCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: TraderStatsAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: TraderStatsSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: TraderStatsMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: TraderStatsMaxAggregateInputType
}

export type GetTraderStatsAggregateType<T extends TraderStatsAggregateArgs> = {
      [P in keyof T & keyof AggregateTraderStats]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateTraderStats[P]>
    : Prisma.GetScalarType<T[P], AggregateTraderStats[P]>
}




export type TraderStatsGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TraderStatsWhereInput
  orderBy?: Prisma.TraderStatsOrderByWithAggregationInput | Prisma.TraderStatsOrderByWithAggregationInput[]
  by: Prisma.TraderStatsScalarFieldEnum[] | Prisma.TraderStatsScalarFieldEnum
  having?: Prisma.TraderStatsScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: TraderStatsCountAggregateInputType | true
  _avg?: TraderStatsAvgAggregateInputType
  _sum?: TraderStatsSumAggregateInputType
  _min?: TraderStatsMinAggregateInputType
  _max?: TraderStatsMaxAggregateInputType
}

export type TraderStatsGroupByOutputType = {
  wallet: string
  tradeCount: number
  resolvedTrades: number
  winCount: number
  winRate: runtime.Decimal
  realisedPnl: runtime.Decimal
  roi: runtime.Decimal
  avgEdge: runtime.Decimal
  score: runtime.Decimal
  firstTradeAt: Date | null
  lastTradeAt: Date | null
  updatedAt: Date
  _count: TraderStatsCountAggregateOutputType | null
  _avg: TraderStatsAvgAggregateOutputType | null
  _sum: TraderStatsSumAggregateOutputType | null
  _min: TraderStatsMinAggregateOutputType | null
  _max: TraderStatsMaxAggregateOutputType | null
}

type GetTraderStatsGroupByPayload<T extends TraderStatsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<TraderStatsGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof TraderStatsGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], TraderStatsGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], TraderStatsGroupByOutputType[P]>
      }
    >
  >



export type TraderStatsWhereInput = {
  AND?: Prisma.TraderStatsWhereInput | Prisma.TraderStatsWhereInput[]
  OR?: Prisma.TraderStatsWhereInput[]
  NOT?: Prisma.TraderStatsWhereInput | Prisma.TraderStatsWhereInput[]
  wallet?: Prisma.StringFilter<"TraderStats"> | string
  tradeCount?: Prisma.IntFilter<"TraderStats"> | number
  resolvedTrades?: Prisma.IntFilter<"TraderStats"> | number
  winCount?: Prisma.IntFilter<"TraderStats"> | number
  winRate?: Prisma.DecimalFilter<"TraderStats"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  realisedPnl?: Prisma.DecimalFilter<"TraderStats"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  roi?: Prisma.DecimalFilter<"TraderStats"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  avgEdge?: Prisma.DecimalFilter<"TraderStats"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  score?: Prisma.DecimalFilter<"TraderStats"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  firstTradeAt?: Prisma.DateTimeNullableFilter<"TraderStats"> | Date | string | null
  lastTradeAt?: Prisma.DateTimeNullableFilter<"TraderStats"> | Date | string | null
  updatedAt?: Prisma.DateTimeFilter<"TraderStats"> | Date | string
}

export type TraderStatsOrderByWithRelationInput = {
  wallet?: Prisma.SortOrder
  tradeCount?: Prisma.SortOrder
  resolvedTrades?: Prisma.SortOrder
  winCount?: Prisma.SortOrder
  winRate?: Prisma.SortOrder
  realisedPnl?: Prisma.SortOrder
  roi?: Prisma.SortOrder
  avgEdge?: Prisma.SortOrder
  score?: Prisma.SortOrder
  firstTradeAt?: Prisma.SortOrderInput | Prisma.SortOrder
  lastTradeAt?: Prisma.SortOrderInput | Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type TraderStatsWhereUniqueInput = Prisma.AtLeast<{
  wallet?: string
  AND?: Prisma.TraderStatsWhereInput | Prisma.TraderStatsWhereInput[]
  OR?: Prisma.TraderStatsWhereInput[]
  NOT?: Prisma.TraderStatsWhereInput | Prisma.TraderStatsWhereInput[]
  tradeCount?: Prisma.IntFilter<"TraderStats"> | number
  resolvedTrades?: Prisma.IntFilter<"TraderStats"> | number
  winCount?: Prisma.IntFilter<"TraderStats"> | number
  winRate?: Prisma.DecimalFilter<"TraderStats"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  realisedPnl?: Prisma.DecimalFilter<"TraderStats"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  roi?: Prisma.DecimalFilter<"TraderStats"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  avgEdge?: Prisma.DecimalFilter<"TraderStats"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  score?: Prisma.DecimalFilter<"TraderStats"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  firstTradeAt?: Prisma.DateTimeNullableFilter<"TraderStats"> | Date | string | null
  lastTradeAt?: Prisma.DateTimeNullableFilter<"TraderStats"> | Date | string | null
  updatedAt?: Prisma.DateTimeFilter<"TraderStats"> | Date | string
}, "wallet">

export type TraderStatsOrderByWithAggregationInput = {
  wallet?: Prisma.SortOrder
  tradeCount?: Prisma.SortOrder
  resolvedTrades?: Prisma.SortOrder
  winCount?: Prisma.SortOrder
  winRate?: Prisma.SortOrder
  realisedPnl?: Prisma.SortOrder
  roi?: Prisma.SortOrder
  avgEdge?: Prisma.SortOrder
  score?: Prisma.SortOrder
  firstTradeAt?: Prisma.SortOrderInput | Prisma.SortOrder
  lastTradeAt?: Prisma.SortOrderInput | Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.TraderStatsCountOrderByAggregateInput
  _avg?: Prisma.TraderStatsAvgOrderByAggregateInput
  _max?: Prisma.TraderStatsMaxOrderByAggregateInput
  _min?: Prisma.TraderStatsMinOrderByAggregateInput
  _sum?: Prisma.TraderStatsSumOrderByAggregateInput
}

export type TraderStatsScalarWhereWithAggregatesInput = {
  AND?: Prisma.TraderStatsScalarWhereWithAggregatesInput | Prisma.TraderStatsScalarWhereWithAggregatesInput[]
  OR?: Prisma.TraderStatsScalarWhereWithAggregatesInput[]
  NOT?: Prisma.TraderStatsScalarWhereWithAggregatesInput | Prisma.TraderStatsScalarWhereWithAggregatesInput[]
  wallet?: Prisma.StringWithAggregatesFilter<"TraderStats"> | string
  tradeCount?: Prisma.IntWithAggregatesFilter<"TraderStats"> | number
  resolvedTrades?: Prisma.IntWithAggregatesFilter<"TraderStats"> | number
  winCount?: Prisma.IntWithAggregatesFilter<"TraderStats"> | number
  winRate?: Prisma.DecimalWithAggregatesFilter<"TraderStats"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  realisedPnl?: Prisma.DecimalWithAggregatesFilter<"TraderStats"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  roi?: Prisma.DecimalWithAggregatesFilter<"TraderStats"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  avgEdge?: Prisma.DecimalWithAggregatesFilter<"TraderStats"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  score?: Prisma.DecimalWithAggregatesFilter<"TraderStats"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  firstTradeAt?: Prisma.DateTimeNullableWithAggregatesFilter<"TraderStats"> | Date | string | null
  lastTradeAt?: Prisma.DateTimeNullableWithAggregatesFilter<"TraderStats"> | Date | string | null
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"TraderStats"> | Date | string
}

export type TraderStatsCreateInput = {
  wallet: string
  tradeCount?: number
  resolvedTrades?: number
  winCount?: number
  winRate?: runtime.Decimal | runtime.DecimalJsLike | number | string
  realisedPnl?: runtime.Decimal | runtime.DecimalJsLike | number | string
  roi?: runtime.Decimal | runtime.DecimalJsLike | number | string
  avgEdge?: runtime.Decimal | runtime.DecimalJsLike | number | string
  score?: runtime.Decimal | runtime.DecimalJsLike | number | string
  firstTradeAt?: Date | string | null
  lastTradeAt?: Date | string | null
  updatedAt?: Date | string
}

export type TraderStatsUncheckedCreateInput = {
  wallet: string
  tradeCount?: number
  resolvedTrades?: number
  winCount?: number
  winRate?: runtime.Decimal | runtime.DecimalJsLike | number | string
  realisedPnl?: runtime.Decimal | runtime.DecimalJsLike | number | string
  roi?: runtime.Decimal | runtime.DecimalJsLike | number | string
  avgEdge?: runtime.Decimal | runtime.DecimalJsLike | number | string
  score?: runtime.Decimal | runtime.DecimalJsLike | number | string
  firstTradeAt?: Date | string | null
  lastTradeAt?: Date | string | null
  updatedAt?: Date | string
}

export type TraderStatsUpdateInput = {
  wallet?: Prisma.StringFieldUpdateOperationsInput | string
  tradeCount?: Prisma.IntFieldUpdateOperationsInput | number
  resolvedTrades?: Prisma.IntFieldUpdateOperationsInput | number
  winCount?: Prisma.IntFieldUpdateOperationsInput | number
  winRate?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  realisedPnl?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  roi?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  avgEdge?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  score?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  firstTradeAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  lastTradeAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TraderStatsUncheckedUpdateInput = {
  wallet?: Prisma.StringFieldUpdateOperationsInput | string
  tradeCount?: Prisma.IntFieldUpdateOperationsInput | number
  resolvedTrades?: Prisma.IntFieldUpdateOperationsInput | number
  winCount?: Prisma.IntFieldUpdateOperationsInput | number
  winRate?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  realisedPnl?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  roi?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  avgEdge?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  score?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  firstTradeAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  lastTradeAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TraderStatsCreateManyInput = {
  wallet: string
  tradeCount?: number
  resolvedTrades?: number
  winCount?: number
  winRate?: runtime.Decimal | runtime.DecimalJsLike | number | string
  realisedPnl?: runtime.Decimal | runtime.DecimalJsLike | number | string
  roi?: runtime.Decimal | runtime.DecimalJsLike | number | string
  avgEdge?: runtime.Decimal | runtime.DecimalJsLike | number | string
  score?: runtime.Decimal | runtime.DecimalJsLike | number | string
  firstTradeAt?: Date | string | null
  lastTradeAt?: Date | string | null
  updatedAt?: Date | string
}

export type TraderStatsUpdateManyMutationInput = {
  wallet?: Prisma.StringFieldUpdateOperationsInput | string
  tradeCount?: Prisma.IntFieldUpdateOperationsInput | number
  resolvedTrades?: Prisma.IntFieldUpdateOperationsInput | number
  winCount?: Prisma.IntFieldUpdateOperationsInput | number
  winRate?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  realisedPnl?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  roi?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  avgEdge?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  score?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  firstTradeAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  lastTradeAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TraderStatsUncheckedUpdateManyInput = {
  wallet?: Prisma.StringFieldUpdateOperationsInput | string
  tradeCount?: Prisma.IntFieldUpdateOperationsInput | number
  resolvedTrades?: Prisma.IntFieldUpdateOperationsInput | number
  winCount?: Prisma.IntFieldUpdateOperationsInput | number
  winRate?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  realisedPnl?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  roi?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  avgEdge?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  score?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  firstTradeAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  lastTradeAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TraderStatsCountOrderByAggregateInput = {
  wallet?: Prisma.SortOrder
  tradeCount?: Prisma.SortOrder
  resolvedTrades?: Prisma.SortOrder
  winCount?: Prisma.SortOrder
  winRate?: Prisma.SortOrder
  realisedPnl?: Prisma.SortOrder
  roi?: Prisma.SortOrder
  avgEdge?: Prisma.SortOrder
  score?: Prisma.SortOrder
  firstTradeAt?: Prisma.SortOrder
  lastTradeAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type TraderStatsAvgOrderByAggregateInput = {
  tradeCount?: Prisma.SortOrder
  resolvedTrades?: Prisma.SortOrder
  winCount?: Prisma.SortOrder
  winRate?: Prisma.SortOrder
  realisedPnl?: Prisma.SortOrder
  roi?: Prisma.SortOrder
  avgEdge?: Prisma.SortOrder
  score?: Prisma.SortOrder
}

export type TraderStatsMaxOrderByAggregateInput = {
  wallet?: Prisma.SortOrder
  tradeCount?: Prisma.SortOrder
  resolvedTrades?: Prisma.SortOrder
  winCount?: Prisma.SortOrder
  winRate?: Prisma.SortOrder
  realisedPnl?: Prisma.SortOrder
  roi?: Prisma.SortOrder
  avgEdge?: Prisma.SortOrder
  score?: Prisma.SortOrder
  firstTradeAt?: Prisma.SortOrder
  lastTradeAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type TraderStatsMinOrderByAggregateInput = {
  wallet?: Prisma.SortOrder
  tradeCount?: Prisma.SortOrder
  resolvedTrades?: Prisma.SortOrder
  winCount?: Prisma.SortOrder
  winRate?: Prisma.SortOrder
  realisedPnl?: Prisma.SortOrder
  roi?: Prisma.SortOrder
  avgEdge?: Prisma.SortOrder
  score?: Prisma.SortOrder
  firstTradeAt?: Prisma.SortOrder
  lastTradeAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type TraderStatsSumOrderByAggregateInput = {
  tradeCount?: Prisma.SortOrder
  resolvedTrades?: Prisma.SortOrder
  winCount?: Prisma.SortOrder
  winRate?: Prisma.SortOrder
  realisedPnl?: Prisma.SortOrder
  roi?: Prisma.SortOrder
  avgEdge?: Prisma.SortOrder
  score?: Prisma.SortOrder
}



export type TraderStatsSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  wallet?: boolean
  tradeCount?: boolean
  resolvedTrades?: boolean
  winCount?: boolean
  winRate?: boolean
  realisedPnl?: boolean
  roi?: boolean
  avgEdge?: boolean
  score?: boolean
  firstTradeAt?: boolean
  lastTradeAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["traderStats"]>

export type TraderStatsSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  wallet?: boolean
  tradeCount?: boolean
  resolvedTrades?: boolean
  winCount?: boolean
  winRate?: boolean
  realisedPnl?: boolean
  roi?: boolean
  avgEdge?: boolean
  score?: boolean
  firstTradeAt?: boolean
  lastTradeAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["traderStats"]>

export type TraderStatsSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  wallet?: boolean
  tradeCount?: boolean
  resolvedTrades?: boolean
  winCount?: boolean
  winRate?: boolean
  realisedPnl?: boolean
  roi?: boolean
  avgEdge?: boolean
  score?: boolean
  firstTradeAt?: boolean
  lastTradeAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["traderStats"]>

export type TraderStatsSelectScalar = {
  wallet?: boolean
  tradeCount?: boolean
  resolvedTrades?: boolean
  winCount?: boolean
  winRate?: boolean
  realisedPnl?: boolean
  roi?: boolean
  avgEdge?: boolean
  score?: boolean
  firstTradeAt?: boolean
  lastTradeAt?: boolean
  updatedAt?: boolean
}

export type TraderStatsOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"wallet" | "tradeCount" | "resolvedTrades" | "winCount" | "winRate" | "realisedPnl" | "roi" | "avgEdge" | "score" | "firstTradeAt" | "lastTradeAt" | "updatedAt", ExtArgs["result"]["traderStats"]>

export type $TraderStatsPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "TraderStats"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    wallet: string
    tradeCount: number
    resolvedTrades: number
    winCount: number
    winRate: runtime.Decimal
    realisedPnl: runtime.Decimal
    roi: runtime.Decimal
    avgEdge: runtime.Decimal
    score: runtime.Decimal
    firstTradeAt: Date | null
    lastTradeAt: Date | null
    updatedAt: Date
  }, ExtArgs["result"]["traderStats"]>
  composites: {}
}

export type TraderStatsGetPayload<S extends boolean | null | undefined | TraderStatsDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$TraderStatsPayload, S>

export type TraderStatsCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<TraderStatsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: TraderStatsCountAggregateInputType | true
  }

export interface TraderStatsDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['TraderStats'], meta: { name: 'TraderStats' } }
  /**
   * Find zero or one TraderStats that matches the filter.
   * @param {TraderStatsFindUniqueArgs} args - Arguments to find a TraderStats
   * @example
   * // Get one TraderStats
   * const traderStats = await prisma.traderStats.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends TraderStatsFindUniqueArgs>(args: Prisma.SelectSubset<T, TraderStatsFindUniqueArgs<ExtArgs>>): Prisma.Prisma__TraderStatsClient<runtime.Types.Result.GetResult<Prisma.$TraderStatsPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one TraderStats that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {TraderStatsFindUniqueOrThrowArgs} args - Arguments to find a TraderStats
   * @example
   * // Get one TraderStats
   * const traderStats = await prisma.traderStats.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends TraderStatsFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, TraderStatsFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__TraderStatsClient<runtime.Types.Result.GetResult<Prisma.$TraderStatsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TraderStats that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TraderStatsFindFirstArgs} args - Arguments to find a TraderStats
   * @example
   * // Get one TraderStats
   * const traderStats = await prisma.traderStats.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends TraderStatsFindFirstArgs>(args?: Prisma.SelectSubset<T, TraderStatsFindFirstArgs<ExtArgs>>): Prisma.Prisma__TraderStatsClient<runtime.Types.Result.GetResult<Prisma.$TraderStatsPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TraderStats that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TraderStatsFindFirstOrThrowArgs} args - Arguments to find a TraderStats
   * @example
   * // Get one TraderStats
   * const traderStats = await prisma.traderStats.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends TraderStatsFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, TraderStatsFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__TraderStatsClient<runtime.Types.Result.GetResult<Prisma.$TraderStatsPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more TraderStats that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TraderStatsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all TraderStats
   * const traderStats = await prisma.traderStats.findMany()
   * 
   * // Get first 10 TraderStats
   * const traderStats = await prisma.traderStats.findMany({ take: 10 })
   * 
   * // Only select the `wallet`
   * const traderStatsWithWalletOnly = await prisma.traderStats.findMany({ select: { wallet: true } })
   * 
   */
  findMany<T extends TraderStatsFindManyArgs>(args?: Prisma.SelectSubset<T, TraderStatsFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TraderStatsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a TraderStats.
   * @param {TraderStatsCreateArgs} args - Arguments to create a TraderStats.
   * @example
   * // Create one TraderStats
   * const TraderStats = await prisma.traderStats.create({
   *   data: {
   *     // ... data to create a TraderStats
   *   }
   * })
   * 
   */
  create<T extends TraderStatsCreateArgs>(args: Prisma.SelectSubset<T, TraderStatsCreateArgs<ExtArgs>>): Prisma.Prisma__TraderStatsClient<runtime.Types.Result.GetResult<Prisma.$TraderStatsPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many TraderStats.
   * @param {TraderStatsCreateManyArgs} args - Arguments to create many TraderStats.
   * @example
   * // Create many TraderStats
   * const traderStats = await prisma.traderStats.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends TraderStatsCreateManyArgs>(args?: Prisma.SelectSubset<T, TraderStatsCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many TraderStats and returns the data saved in the database.
   * @param {TraderStatsCreateManyAndReturnArgs} args - Arguments to create many TraderStats.
   * @example
   * // Create many TraderStats
   * const traderStats = await prisma.traderStats.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many TraderStats and only return the `wallet`
   * const traderStatsWithWalletOnly = await prisma.traderStats.createManyAndReturn({
   *   select: { wallet: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends TraderStatsCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, TraderStatsCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TraderStatsPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a TraderStats.
   * @param {TraderStatsDeleteArgs} args - Arguments to delete one TraderStats.
   * @example
   * // Delete one TraderStats
   * const TraderStats = await prisma.traderStats.delete({
   *   where: {
   *     // ... filter to delete one TraderStats
   *   }
   * })
   * 
   */
  delete<T extends TraderStatsDeleteArgs>(args: Prisma.SelectSubset<T, TraderStatsDeleteArgs<ExtArgs>>): Prisma.Prisma__TraderStatsClient<runtime.Types.Result.GetResult<Prisma.$TraderStatsPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one TraderStats.
   * @param {TraderStatsUpdateArgs} args - Arguments to update one TraderStats.
   * @example
   * // Update one TraderStats
   * const traderStats = await prisma.traderStats.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends TraderStatsUpdateArgs>(args: Prisma.SelectSubset<T, TraderStatsUpdateArgs<ExtArgs>>): Prisma.Prisma__TraderStatsClient<runtime.Types.Result.GetResult<Prisma.$TraderStatsPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more TraderStats.
   * @param {TraderStatsDeleteManyArgs} args - Arguments to filter TraderStats to delete.
   * @example
   * // Delete a few TraderStats
   * const { count } = await prisma.traderStats.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends TraderStatsDeleteManyArgs>(args?: Prisma.SelectSubset<T, TraderStatsDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TraderStats.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TraderStatsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many TraderStats
   * const traderStats = await prisma.traderStats.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends TraderStatsUpdateManyArgs>(args: Prisma.SelectSubset<T, TraderStatsUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TraderStats and returns the data updated in the database.
   * @param {TraderStatsUpdateManyAndReturnArgs} args - Arguments to update many TraderStats.
   * @example
   * // Update many TraderStats
   * const traderStats = await prisma.traderStats.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more TraderStats and only return the `wallet`
   * const traderStatsWithWalletOnly = await prisma.traderStats.updateManyAndReturn({
   *   select: { wallet: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends TraderStatsUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, TraderStatsUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TraderStatsPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one TraderStats.
   * @param {TraderStatsUpsertArgs} args - Arguments to update or create a TraderStats.
   * @example
   * // Update or create a TraderStats
   * const traderStats = await prisma.traderStats.upsert({
   *   create: {
   *     // ... data to create a TraderStats
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the TraderStats we want to update
   *   }
   * })
   */
  upsert<T extends TraderStatsUpsertArgs>(args: Prisma.SelectSubset<T, TraderStatsUpsertArgs<ExtArgs>>): Prisma.Prisma__TraderStatsClient<runtime.Types.Result.GetResult<Prisma.$TraderStatsPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of TraderStats.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TraderStatsCountArgs} args - Arguments to filter TraderStats to count.
   * @example
   * // Count the number of TraderStats
   * const count = await prisma.traderStats.count({
   *   where: {
   *     // ... the filter for the TraderStats we want to count
   *   }
   * })
  **/
  count<T extends TraderStatsCountArgs>(
    args?: Prisma.Subset<T, TraderStatsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], TraderStatsCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a TraderStats.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TraderStatsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends TraderStatsAggregateArgs>(args: Prisma.Subset<T, TraderStatsAggregateArgs>): Prisma.PrismaPromise<GetTraderStatsAggregateType<T>>

  /**
   * Group by TraderStats.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TraderStatsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends TraderStatsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: TraderStatsGroupByArgs['orderBy'] }
      : { orderBy?: TraderStatsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, TraderStatsGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetTraderStatsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the TraderStats model
 */
readonly fields: TraderStatsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for TraderStats.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__TraderStatsClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the TraderStats model
 */
export interface TraderStatsFieldRefs {
  readonly wallet: Prisma.FieldRef<"TraderStats", 'String'>
  readonly tradeCount: Prisma.FieldRef<"TraderStats", 'Int'>
  readonly resolvedTrades: Prisma.FieldRef<"TraderStats", 'Int'>
  readonly winCount: Prisma.FieldRef<"TraderStats", 'Int'>
  readonly winRate: Prisma.FieldRef<"TraderStats", 'Decimal'>
  readonly realisedPnl: Prisma.FieldRef<"TraderStats", 'Decimal'>
  readonly roi: Prisma.FieldRef<"TraderStats", 'Decimal'>
  readonly avgEdge: Prisma.FieldRef<"TraderStats", 'Decimal'>
  readonly score: Prisma.FieldRef<"TraderStats", 'Decimal'>
  readonly firstTradeAt: Prisma.FieldRef<"TraderStats", 'DateTime'>
  readonly lastTradeAt: Prisma.FieldRef<"TraderStats", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"TraderStats", 'DateTime'>
}
    

// Custom InputTypes
/**
 * TraderStats findUnique
 */
export type TraderStatsFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TraderStats
   */
  select?: Prisma.TraderStatsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TraderStats
   */
  omit?: Prisma.TraderStatsOmit<ExtArgs> | null
  /**
   * Filter, which TraderStats to fetch.
   */
  where: Prisma.TraderStatsWhereUniqueInput
}

/**
 * TraderStats findUniqueOrThrow
 */
export type TraderStatsFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TraderStats
   */
  select?: Prisma.TraderStatsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TraderStats
   */
  omit?: Prisma.TraderStatsOmit<ExtArgs> | null
  /**
   * Filter, which TraderStats to fetch.
   */
  where: Prisma.TraderStatsWhereUniqueInput
}

/**
 * TraderStats findFirst
 */
export type TraderStatsFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TraderStats
   */
  select?: Prisma.TraderStatsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TraderStats
   */
  omit?: Prisma.TraderStatsOmit<ExtArgs> | null
  /**
   * Filter, which TraderStats to fetch.
   */
  where?: Prisma.TraderStatsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TraderStats to fetch.
   */
  orderBy?: Prisma.TraderStatsOrderByWithRelationInput | Prisma.TraderStatsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TraderStats.
   */
  cursor?: Prisma.TraderStatsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TraderStats from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TraderStats.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TraderStats.
   */
  distinct?: Prisma.TraderStatsScalarFieldEnum | Prisma.TraderStatsScalarFieldEnum[]
}

/**
 * TraderStats findFirstOrThrow
 */
export type TraderStatsFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TraderStats
   */
  select?: Prisma.TraderStatsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TraderStats
   */
  omit?: Prisma.TraderStatsOmit<ExtArgs> | null
  /**
   * Filter, which TraderStats to fetch.
   */
  where?: Prisma.TraderStatsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TraderStats to fetch.
   */
  orderBy?: Prisma.TraderStatsOrderByWithRelationInput | Prisma.TraderStatsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TraderStats.
   */
  cursor?: Prisma.TraderStatsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TraderStats from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TraderStats.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TraderStats.
   */
  distinct?: Prisma.TraderStatsScalarFieldEnum | Prisma.TraderStatsScalarFieldEnum[]
}

/**
 * TraderStats findMany
 */
export type TraderStatsFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TraderStats
   */
  select?: Prisma.TraderStatsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TraderStats
   */
  omit?: Prisma.TraderStatsOmit<ExtArgs> | null
  /**
   * Filter, which TraderStats to fetch.
   */
  where?: Prisma.TraderStatsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TraderStats to fetch.
   */
  orderBy?: Prisma.TraderStatsOrderByWithRelationInput | Prisma.TraderStatsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing TraderStats.
   */
  cursor?: Prisma.TraderStatsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TraderStats from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TraderStats.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TraderStats.
   */
  distinct?: Prisma.TraderStatsScalarFieldEnum | Prisma.TraderStatsScalarFieldEnum[]
}

/**
 * TraderStats create
 */
export type TraderStatsCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TraderStats
   */
  select?: Prisma.TraderStatsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TraderStats
   */
  omit?: Prisma.TraderStatsOmit<ExtArgs> | null
  /**
   * The data needed to create a TraderStats.
   */
  data: Prisma.XOR<Prisma.TraderStatsCreateInput, Prisma.TraderStatsUncheckedCreateInput>
}

/**
 * TraderStats createMany
 */
export type TraderStatsCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many TraderStats.
   */
  data: Prisma.TraderStatsCreateManyInput | Prisma.TraderStatsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * TraderStats createManyAndReturn
 */
export type TraderStatsCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TraderStats
   */
  select?: Prisma.TraderStatsSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TraderStats
   */
  omit?: Prisma.TraderStatsOmit<ExtArgs> | null
  /**
   * The data used to create many TraderStats.
   */
  data: Prisma.TraderStatsCreateManyInput | Prisma.TraderStatsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * TraderStats update
 */
export type TraderStatsUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TraderStats
   */
  select?: Prisma.TraderStatsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TraderStats
   */
  omit?: Prisma.TraderStatsOmit<ExtArgs> | null
  /**
   * The data needed to update a TraderStats.
   */
  data: Prisma.XOR<Prisma.TraderStatsUpdateInput, Prisma.TraderStatsUncheckedUpdateInput>
  /**
   * Choose, which TraderStats to update.
   */
  where: Prisma.TraderStatsWhereUniqueInput
}

/**
 * TraderStats updateMany
 */
export type TraderStatsUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update TraderStats.
   */
  data: Prisma.XOR<Prisma.TraderStatsUpdateManyMutationInput, Prisma.TraderStatsUncheckedUpdateManyInput>
  /**
   * Filter which TraderStats to update
   */
  where?: Prisma.TraderStatsWhereInput
  /**
   * Limit how many TraderStats to update.
   */
  limit?: number
}

/**
 * TraderStats updateManyAndReturn
 */
export type TraderStatsUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TraderStats
   */
  select?: Prisma.TraderStatsSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TraderStats
   */
  omit?: Prisma.TraderStatsOmit<ExtArgs> | null
  /**
   * The data used to update TraderStats.
   */
  data: Prisma.XOR<Prisma.TraderStatsUpdateManyMutationInput, Prisma.TraderStatsUncheckedUpdateManyInput>
  /**
   * Filter which TraderStats to update
   */
  where?: Prisma.TraderStatsWhereInput
  /**
   * Limit how many TraderStats to update.
   */
  limit?: number
}

/**
 * TraderStats upsert
 */
export type TraderStatsUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TraderStats
   */
  select?: Prisma.TraderStatsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TraderStats
   */
  omit?: Prisma.TraderStatsOmit<ExtArgs> | null
  /**
   * The filter to search for the TraderStats to update in case it exists.
   */
  where: Prisma.TraderStatsWhereUniqueInput
  /**
   * In case the TraderStats found by the `where` argument doesn't exist, create a new TraderStats with this data.
   */
  create: Prisma.XOR<Prisma.TraderStatsCreateInput, Prisma.TraderStatsUncheckedCreateInput>
  /**
   * In case the TraderStats was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.TraderStatsUpdateInput, Prisma.TraderStatsUncheckedUpdateInput>
}

/**
 * TraderStats delete
 */
export type TraderStatsDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TraderStats
   */
  select?: Prisma.TraderStatsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TraderStats
   */
  omit?: Prisma.TraderStatsOmit<ExtArgs> | null
  /**
   * Filter which TraderStats to delete.
   */
  where: Prisma.TraderStatsWhereUniqueInput
}

/**
 * TraderStats deleteMany
 */
export type TraderStatsDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TraderStats to delete
   */
  where?: Prisma.TraderStatsWhereInput
  /**
   * Limit how many TraderStats to delete.
   */
  limit?: number
}

/**
 * TraderStats without action
 */
export type TraderStatsDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TraderStats
   */
  select?: Prisma.TraderStatsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TraderStats
   */
  omit?: Prisma.TraderStatsOmit<ExtArgs> | null
}
