
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Watchlist` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model Watchlist
 * 
 */
export type WatchlistModel = runtime.Types.Result.DefaultSelection<Prisma.$WatchlistPayload>

export type AggregateWatchlist = {
  _count: WatchlistCountAggregateOutputType | null
  _avg: WatchlistAvgAggregateOutputType | null
  _sum: WatchlistSumAggregateOutputType | null
  _min: WatchlistMinAggregateOutputType | null
  _max: WatchlistMaxAggregateOutputType | null
}

export type WatchlistAvgAggregateOutputType = {
  score: runtime.Decimal | null
}

export type WatchlistSumAggregateOutputType = {
  score: runtime.Decimal | null
}

export type WatchlistMinAggregateOutputType = {
  wallet: string | null
  reason: string | null
  score: runtime.Decimal | null
  active: boolean | null
  addedAt: Date | null
  removedAt: Date | null
}

export type WatchlistMaxAggregateOutputType = {
  wallet: string | null
  reason: string | null
  score: runtime.Decimal | null
  active: boolean | null
  addedAt: Date | null
  removedAt: Date | null
}

export type WatchlistCountAggregateOutputType = {
  wallet: number
  reason: number
  score: number
  active: number
  addedAt: number
  removedAt: number
  _all: number
}


export type WatchlistAvgAggregateInputType = {
  score?: true
}

export type WatchlistSumAggregateInputType = {
  score?: true
}

export type WatchlistMinAggregateInputType = {
  wallet?: true
  reason?: true
  score?: true
  active?: true
  addedAt?: true
  removedAt?: true
}

export type WatchlistMaxAggregateInputType = {
  wallet?: true
  reason?: true
  score?: true
  active?: true
  addedAt?: true
  removedAt?: true
}

export type WatchlistCountAggregateInputType = {
  wallet?: true
  reason?: true
  score?: true
  active?: true
  addedAt?: true
  removedAt?: true
  _all?: true
}

export type WatchlistAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Watchlist to aggregate.
   */
  where?: Prisma.WatchlistWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Watchlists to fetch.
   */
  orderBy?: Prisma.WatchlistOrderByWithRelationInput | Prisma.WatchlistOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.WatchlistWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Watchlists from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Watchlists.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Watchlists
  **/
  _count?: true | WatchlistCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: WatchlistAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: WatchlistSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: WatchlistMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: WatchlistMaxAggregateInputType
}

export type GetWatchlistAggregateType<T extends WatchlistAggregateArgs> = {
      [P in keyof T & keyof AggregateWatchlist]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateWatchlist[P]>
    : Prisma.GetScalarType<T[P], AggregateWatchlist[P]>
}




export type WatchlistGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.WatchlistWhereInput
  orderBy?: Prisma.WatchlistOrderByWithAggregationInput | Prisma.WatchlistOrderByWithAggregationInput[]
  by: Prisma.WatchlistScalarFieldEnum[] | Prisma.WatchlistScalarFieldEnum
  having?: Prisma.WatchlistScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: WatchlistCountAggregateInputType | true
  _avg?: WatchlistAvgAggregateInputType
  _sum?: WatchlistSumAggregateInputType
  _min?: WatchlistMinAggregateInputType
  _max?: WatchlistMaxAggregateInputType
}

export type WatchlistGroupByOutputType = {
  wallet: string
  reason: string
  score: runtime.Decimal
  active: boolean
  addedAt: Date
  removedAt: Date | null
  _count: WatchlistCountAggregateOutputType | null
  _avg: WatchlistAvgAggregateOutputType | null
  _sum: WatchlistSumAggregateOutputType | null
  _min: WatchlistMinAggregateOutputType | null
  _max: WatchlistMaxAggregateOutputType | null
}

type GetWatchlistGroupByPayload<T extends WatchlistGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<WatchlistGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof WatchlistGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], WatchlistGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], WatchlistGroupByOutputType[P]>
      }
    >
  >



export type WatchlistWhereInput = {
  AND?: Prisma.WatchlistWhereInput | Prisma.WatchlistWhereInput[]
  OR?: Prisma.WatchlistWhereInput[]
  NOT?: Prisma.WatchlistWhereInput | Prisma.WatchlistWhereInput[]
  wallet?: Prisma.StringFilter<"Watchlist"> | string
  reason?: Prisma.StringFilter<"Watchlist"> | string
  score?: Prisma.DecimalFilter<"Watchlist"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  active?: Prisma.BoolFilter<"Watchlist"> | boolean
  addedAt?: Prisma.DateTimeFilter<"Watchlist"> | Date | string
  removedAt?: Prisma.DateTimeNullableFilter<"Watchlist"> | Date | string | null
}

export type WatchlistOrderByWithRelationInput = {
  wallet?: Prisma.SortOrder
  reason?: Prisma.SortOrder
  score?: Prisma.SortOrder
  active?: Prisma.SortOrder
  addedAt?: Prisma.SortOrder
  removedAt?: Prisma.SortOrderInput | Prisma.SortOrder
}

export type WatchlistWhereUniqueInput = Prisma.AtLeast<{
  wallet?: string
  AND?: Prisma.WatchlistWhereInput | Prisma.WatchlistWhereInput[]
  OR?: Prisma.WatchlistWhereInput[]
  NOT?: Prisma.WatchlistWhereInput | Prisma.WatchlistWhereInput[]
  reason?: Prisma.StringFilter<"Watchlist"> | string
  score?: Prisma.DecimalFilter<"Watchlist"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  active?: Prisma.BoolFilter<"Watchlist"> | boolean
  addedAt?: Prisma.DateTimeFilter<"Watchlist"> | Date | string
  removedAt?: Prisma.DateTimeNullableFilter<"Watchlist"> | Date | string | null
}, "wallet">

export type WatchlistOrderByWithAggregationInput = {
  wallet?: Prisma.SortOrder
  reason?: Prisma.SortOrder
  score?: Prisma.SortOrder
  active?: Prisma.SortOrder
  addedAt?: Prisma.SortOrder
  removedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.WatchlistCountOrderByAggregateInput
  _avg?: Prisma.WatchlistAvgOrderByAggregateInput
  _max?: Prisma.WatchlistMaxOrderByAggregateInput
  _min?: Prisma.WatchlistMinOrderByAggregateInput
  _sum?: Prisma.WatchlistSumOrderByAggregateInput
}

export type WatchlistScalarWhereWithAggregatesInput = {
  AND?: Prisma.WatchlistScalarWhereWithAggregatesInput | Prisma.WatchlistScalarWhereWithAggregatesInput[]
  OR?: Prisma.WatchlistScalarWhereWithAggregatesInput[]
  NOT?: Prisma.WatchlistScalarWhereWithAggregatesInput | Prisma.WatchlistScalarWhereWithAggregatesInput[]
  wallet?: Prisma.StringWithAggregatesFilter<"Watchlist"> | string
  reason?: Prisma.StringWithAggregatesFilter<"Watchlist"> | string
  score?: Prisma.DecimalWithAggregatesFilter<"Watchlist"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  active?: Prisma.BoolWithAggregatesFilter<"Watchlist"> | boolean
  addedAt?: Prisma.DateTimeWithAggregatesFilter<"Watchlist"> | Date | string
  removedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"Watchlist"> | Date | string | null
}

export type WatchlistCreateInput = {
  wallet: string
  reason: string
  score: runtime.Decimal | runtime.DecimalJsLike | number | string
  active?: boolean
  addedAt?: Date | string
  removedAt?: Date | string | null
}

export type WatchlistUncheckedCreateInput = {
  wallet: string
  reason: string
  score: runtime.Decimal | runtime.DecimalJsLike | number | string
  active?: boolean
  addedAt?: Date | string
  removedAt?: Date | string | null
}

export type WatchlistUpdateInput = {
  wallet?: Prisma.StringFieldUpdateOperationsInput | string
  reason?: Prisma.StringFieldUpdateOperationsInput | string
  score?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  addedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  removedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type WatchlistUncheckedUpdateInput = {
  wallet?: Prisma.StringFieldUpdateOperationsInput | string
  reason?: Prisma.StringFieldUpdateOperationsInput | string
  score?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  addedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  removedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type WatchlistCreateManyInput = {
  wallet: string
  reason: string
  score: runtime.Decimal | runtime.DecimalJsLike | number | string
  active?: boolean
  addedAt?: Date | string
  removedAt?: Date | string | null
}

export type WatchlistUpdateManyMutationInput = {
  wallet?: Prisma.StringFieldUpdateOperationsInput | string
  reason?: Prisma.StringFieldUpdateOperationsInput | string
  score?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  addedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  removedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type WatchlistUncheckedUpdateManyInput = {
  wallet?: Prisma.StringFieldUpdateOperationsInput | string
  reason?: Prisma.StringFieldUpdateOperationsInput | string
  score?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  addedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  removedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type WatchlistCountOrderByAggregateInput = {
  wallet?: Prisma.SortOrder
  reason?: Prisma.SortOrder
  score?: Prisma.SortOrder
  active?: Prisma.SortOrder
  addedAt?: Prisma.SortOrder
  removedAt?: Prisma.SortOrder
}

export type WatchlistAvgOrderByAggregateInput = {
  score?: Prisma.SortOrder
}

export type WatchlistMaxOrderByAggregateInput = {
  wallet?: Prisma.SortOrder
  reason?: Prisma.SortOrder
  score?: Prisma.SortOrder
  active?: Prisma.SortOrder
  addedAt?: Prisma.SortOrder
  removedAt?: Prisma.SortOrder
}

export type WatchlistMinOrderByAggregateInput = {
  wallet?: Prisma.SortOrder
  reason?: Prisma.SortOrder
  score?: Prisma.SortOrder
  active?: Prisma.SortOrder
  addedAt?: Prisma.SortOrder
  removedAt?: Prisma.SortOrder
}

export type WatchlistSumOrderByAggregateInput = {
  score?: Prisma.SortOrder
}

export type BoolFieldUpdateOperationsInput = {
  set?: boolean
}



export type WatchlistSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  wallet?: boolean
  reason?: boolean
  score?: boolean
  active?: boolean
  addedAt?: boolean
  removedAt?: boolean
}, ExtArgs["result"]["watchlist"]>

export type WatchlistSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  wallet?: boolean
  reason?: boolean
  score?: boolean
  active?: boolean
  addedAt?: boolean
  removedAt?: boolean
}, ExtArgs["result"]["watchlist"]>

export type WatchlistSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  wallet?: boolean
  reason?: boolean
  score?: boolean
  active?: boolean
  addedAt?: boolean
  removedAt?: boolean
}, ExtArgs["result"]["watchlist"]>

export type WatchlistSelectScalar = {
  wallet?: boolean
  reason?: boolean
  score?: boolean
  active?: boolean
  addedAt?: boolean
  removedAt?: boolean
}

export type WatchlistOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"wallet" | "reason" | "score" | "active" | "addedAt" | "removedAt", ExtArgs["result"]["watchlist"]>

export type $WatchlistPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Watchlist"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    wallet: string
    reason: string
    score: runtime.Decimal
    active: boolean
    addedAt: Date
    removedAt: Date | null
  }, ExtArgs["result"]["watchlist"]>
  composites: {}
}

export type WatchlistGetPayload<S extends boolean | null | undefined | WatchlistDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$WatchlistPayload, S>

export type WatchlistCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<WatchlistFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: WatchlistCountAggregateInputType | true
  }

export interface WatchlistDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Watchlist'], meta: { name: 'Watchlist' } }
  /**
   * Find zero or one Watchlist that matches the filter.
   * @param {WatchlistFindUniqueArgs} args - Arguments to find a Watchlist
   * @example
   * // Get one Watchlist
   * const watchlist = await prisma.watchlist.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends WatchlistFindUniqueArgs>(args: Prisma.SelectSubset<T, WatchlistFindUniqueArgs<ExtArgs>>): Prisma.Prisma__WatchlistClient<runtime.Types.Result.GetResult<Prisma.$WatchlistPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Watchlist that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {WatchlistFindUniqueOrThrowArgs} args - Arguments to find a Watchlist
   * @example
   * // Get one Watchlist
   * const watchlist = await prisma.watchlist.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends WatchlistFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, WatchlistFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__WatchlistClient<runtime.Types.Result.GetResult<Prisma.$WatchlistPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Watchlist that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WatchlistFindFirstArgs} args - Arguments to find a Watchlist
   * @example
   * // Get one Watchlist
   * const watchlist = await prisma.watchlist.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends WatchlistFindFirstArgs>(args?: Prisma.SelectSubset<T, WatchlistFindFirstArgs<ExtArgs>>): Prisma.Prisma__WatchlistClient<runtime.Types.Result.GetResult<Prisma.$WatchlistPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Watchlist that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WatchlistFindFirstOrThrowArgs} args - Arguments to find a Watchlist
   * @example
   * // Get one Watchlist
   * const watchlist = await prisma.watchlist.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends WatchlistFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, WatchlistFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__WatchlistClient<runtime.Types.Result.GetResult<Prisma.$WatchlistPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Watchlists that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WatchlistFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Watchlists
   * const watchlists = await prisma.watchlist.findMany()
   * 
   * // Get first 10 Watchlists
   * const watchlists = await prisma.watchlist.findMany({ take: 10 })
   * 
   * // Only select the `wallet`
   * const watchlistWithWalletOnly = await prisma.watchlist.findMany({ select: { wallet: true } })
   * 
   */
  findMany<T extends WatchlistFindManyArgs>(args?: Prisma.SelectSubset<T, WatchlistFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$WatchlistPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Watchlist.
   * @param {WatchlistCreateArgs} args - Arguments to create a Watchlist.
   * @example
   * // Create one Watchlist
   * const Watchlist = await prisma.watchlist.create({
   *   data: {
   *     // ... data to create a Watchlist
   *   }
   * })
   * 
   */
  create<T extends WatchlistCreateArgs>(args: Prisma.SelectSubset<T, WatchlistCreateArgs<ExtArgs>>): Prisma.Prisma__WatchlistClient<runtime.Types.Result.GetResult<Prisma.$WatchlistPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Watchlists.
   * @param {WatchlistCreateManyArgs} args - Arguments to create many Watchlists.
   * @example
   * // Create many Watchlists
   * const watchlist = await prisma.watchlist.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends WatchlistCreateManyArgs>(args?: Prisma.SelectSubset<T, WatchlistCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Watchlists and returns the data saved in the database.
   * @param {WatchlistCreateManyAndReturnArgs} args - Arguments to create many Watchlists.
   * @example
   * // Create many Watchlists
   * const watchlist = await prisma.watchlist.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Watchlists and only return the `wallet`
   * const watchlistWithWalletOnly = await prisma.watchlist.createManyAndReturn({
   *   select: { wallet: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends WatchlistCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, WatchlistCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$WatchlistPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Watchlist.
   * @param {WatchlistDeleteArgs} args - Arguments to delete one Watchlist.
   * @example
   * // Delete one Watchlist
   * const Watchlist = await prisma.watchlist.delete({
   *   where: {
   *     // ... filter to delete one Watchlist
   *   }
   * })
   * 
   */
  delete<T extends WatchlistDeleteArgs>(args: Prisma.SelectSubset<T, WatchlistDeleteArgs<ExtArgs>>): Prisma.Prisma__WatchlistClient<runtime.Types.Result.GetResult<Prisma.$WatchlistPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Watchlist.
   * @param {WatchlistUpdateArgs} args - Arguments to update one Watchlist.
   * @example
   * // Update one Watchlist
   * const watchlist = await prisma.watchlist.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends WatchlistUpdateArgs>(args: Prisma.SelectSubset<T, WatchlistUpdateArgs<ExtArgs>>): Prisma.Prisma__WatchlistClient<runtime.Types.Result.GetResult<Prisma.$WatchlistPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Watchlists.
   * @param {WatchlistDeleteManyArgs} args - Arguments to filter Watchlists to delete.
   * @example
   * // Delete a few Watchlists
   * const { count } = await prisma.watchlist.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends WatchlistDeleteManyArgs>(args?: Prisma.SelectSubset<T, WatchlistDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Watchlists.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WatchlistUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Watchlists
   * const watchlist = await prisma.watchlist.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends WatchlistUpdateManyArgs>(args: Prisma.SelectSubset<T, WatchlistUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Watchlists and returns the data updated in the database.
   * @param {WatchlistUpdateManyAndReturnArgs} args - Arguments to update many Watchlists.
   * @example
   * // Update many Watchlists
   * const watchlist = await prisma.watchlist.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Watchlists and only return the `wallet`
   * const watchlistWithWalletOnly = await prisma.watchlist.updateManyAndReturn({
   *   select: { wallet: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends WatchlistUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, WatchlistUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$WatchlistPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Watchlist.
   * @param {WatchlistUpsertArgs} args - Arguments to update or create a Watchlist.
   * @example
   * // Update or create a Watchlist
   * const watchlist = await prisma.watchlist.upsert({
   *   create: {
   *     // ... data to create a Watchlist
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Watchlist we want to update
   *   }
   * })
   */
  upsert<T extends WatchlistUpsertArgs>(args: Prisma.SelectSubset<T, WatchlistUpsertArgs<ExtArgs>>): Prisma.Prisma__WatchlistClient<runtime.Types.Result.GetResult<Prisma.$WatchlistPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Watchlists.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WatchlistCountArgs} args - Arguments to filter Watchlists to count.
   * @example
   * // Count the number of Watchlists
   * const count = await prisma.watchlist.count({
   *   where: {
   *     // ... the filter for the Watchlists we want to count
   *   }
   * })
  **/
  count<T extends WatchlistCountArgs>(
    args?: Prisma.Subset<T, WatchlistCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], WatchlistCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Watchlist.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WatchlistAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends WatchlistAggregateArgs>(args: Prisma.Subset<T, WatchlistAggregateArgs>): Prisma.PrismaPromise<GetWatchlistAggregateType<T>>

  /**
   * Group by Watchlist.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WatchlistGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends WatchlistGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: WatchlistGroupByArgs['orderBy'] }
      : { orderBy?: WatchlistGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, WatchlistGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetWatchlistGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Watchlist model
 */
readonly fields: WatchlistFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Watchlist.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__WatchlistClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Watchlist model
 */
export interface WatchlistFieldRefs {
  readonly wallet: Prisma.FieldRef<"Watchlist", 'String'>
  readonly reason: Prisma.FieldRef<"Watchlist", 'String'>
  readonly score: Prisma.FieldRef<"Watchlist", 'Decimal'>
  readonly active: Prisma.FieldRef<"Watchlist", 'Boolean'>
  readonly addedAt: Prisma.FieldRef<"Watchlist", 'DateTime'>
  readonly removedAt: Prisma.FieldRef<"Watchlist", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Watchlist findUnique
 */
export type WatchlistFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Watchlist
   */
  select?: Prisma.WatchlistSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Watchlist
   */
  omit?: Prisma.WatchlistOmit<ExtArgs> | null
  /**
   * Filter, which Watchlist to fetch.
   */
  where: Prisma.WatchlistWhereUniqueInput
}

/**
 * Watchlist findUniqueOrThrow
 */
export type WatchlistFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Watchlist
   */
  select?: Prisma.WatchlistSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Watchlist
   */
  omit?: Prisma.WatchlistOmit<ExtArgs> | null
  /**
   * Filter, which Watchlist to fetch.
   */
  where: Prisma.WatchlistWhereUniqueInput
}

/**
 * Watchlist findFirst
 */
export type WatchlistFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Watchlist
   */
  select?: Prisma.WatchlistSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Watchlist
   */
  omit?: Prisma.WatchlistOmit<ExtArgs> | null
  /**
   * Filter, which Watchlist to fetch.
   */
  where?: Prisma.WatchlistWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Watchlists to fetch.
   */
  orderBy?: Prisma.WatchlistOrderByWithRelationInput | Prisma.WatchlistOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Watchlists.
   */
  cursor?: Prisma.WatchlistWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Watchlists from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Watchlists.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Watchlists.
   */
  distinct?: Prisma.WatchlistScalarFieldEnum | Prisma.WatchlistScalarFieldEnum[]
}

/**
 * Watchlist findFirstOrThrow
 */
export type WatchlistFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Watchlist
   */
  select?: Prisma.WatchlistSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Watchlist
   */
  omit?: Prisma.WatchlistOmit<ExtArgs> | null
  /**
   * Filter, which Watchlist to fetch.
   */
  where?: Prisma.WatchlistWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Watchlists to fetch.
   */
  orderBy?: Prisma.WatchlistOrderByWithRelationInput | Prisma.WatchlistOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Watchlists.
   */
  cursor?: Prisma.WatchlistWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Watchlists from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Watchlists.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Watchlists.
   */
  distinct?: Prisma.WatchlistScalarFieldEnum | Prisma.WatchlistScalarFieldEnum[]
}

/**
 * Watchlist findMany
 */
export type WatchlistFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Watchlist
   */
  select?: Prisma.WatchlistSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Watchlist
   */
  omit?: Prisma.WatchlistOmit<ExtArgs> | null
  /**
   * Filter, which Watchlists to fetch.
   */
  where?: Prisma.WatchlistWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Watchlists to fetch.
   */
  orderBy?: Prisma.WatchlistOrderByWithRelationInput | Prisma.WatchlistOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Watchlists.
   */
  cursor?: Prisma.WatchlistWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Watchlists from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Watchlists.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Watchlists.
   */
  distinct?: Prisma.WatchlistScalarFieldEnum | Prisma.WatchlistScalarFieldEnum[]
}

/**
 * Watchlist create
 */
export type WatchlistCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Watchlist
   */
  select?: Prisma.WatchlistSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Watchlist
   */
  omit?: Prisma.WatchlistOmit<ExtArgs> | null
  /**
   * The data needed to create a Watchlist.
   */
  data: Prisma.XOR<Prisma.WatchlistCreateInput, Prisma.WatchlistUncheckedCreateInput>
}

/**
 * Watchlist createMany
 */
export type WatchlistCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Watchlists.
   */
  data: Prisma.WatchlistCreateManyInput | Prisma.WatchlistCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Watchlist createManyAndReturn
 */
export type WatchlistCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Watchlist
   */
  select?: Prisma.WatchlistSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Watchlist
   */
  omit?: Prisma.WatchlistOmit<ExtArgs> | null
  /**
   * The data used to create many Watchlists.
   */
  data: Prisma.WatchlistCreateManyInput | Prisma.WatchlistCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Watchlist update
 */
export type WatchlistUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Watchlist
   */
  select?: Prisma.WatchlistSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Watchlist
   */
  omit?: Prisma.WatchlistOmit<ExtArgs> | null
  /**
   * The data needed to update a Watchlist.
   */
  data: Prisma.XOR<Prisma.WatchlistUpdateInput, Prisma.WatchlistUncheckedUpdateInput>
  /**
   * Choose, which Watchlist to update.
   */
  where: Prisma.WatchlistWhereUniqueInput
}

/**
 * Watchlist updateMany
 */
export type WatchlistUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Watchlists.
   */
  data: Prisma.XOR<Prisma.WatchlistUpdateManyMutationInput, Prisma.WatchlistUncheckedUpdateManyInput>
  /**
   * Filter which Watchlists to update
   */
  where?: Prisma.WatchlistWhereInput
  /**
   * Limit how many Watchlists to update.
   */
  limit?: number
}

/**
 * Watchlist updateManyAndReturn
 */
export type WatchlistUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Watchlist
   */
  select?: Prisma.WatchlistSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Watchlist
   */
  omit?: Prisma.WatchlistOmit<ExtArgs> | null
  /**
   * The data used to update Watchlists.
   */
  data: Prisma.XOR<Prisma.WatchlistUpdateManyMutationInput, Prisma.WatchlistUncheckedUpdateManyInput>
  /**
   * Filter which Watchlists to update
   */
  where?: Prisma.WatchlistWhereInput
  /**
   * Limit how many Watchlists to update.
   */
  limit?: number
}

/**
 * Watchlist upsert
 */
export type WatchlistUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Watchlist
   */
  select?: Prisma.WatchlistSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Watchlist
   */
  omit?: Prisma.WatchlistOmit<ExtArgs> | null
  /**
   * The filter to search for the Watchlist to update in case it exists.
   */
  where: Prisma.WatchlistWhereUniqueInput
  /**
   * In case the Watchlist found by the `where` argument doesn't exist, create a new Watchlist with this data.
   */
  create: Prisma.XOR<Prisma.WatchlistCreateInput, Prisma.WatchlistUncheckedCreateInput>
  /**
   * In case the Watchlist was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.WatchlistUpdateInput, Prisma.WatchlistUncheckedUpdateInput>
}

/**
 * Watchlist delete
 */
export type WatchlistDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Watchlist
   */
  select?: Prisma.WatchlistSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Watchlist
   */
  omit?: Prisma.WatchlistOmit<ExtArgs> | null
  /**
   * Filter which Watchlist to delete.
   */
  where: Prisma.WatchlistWhereUniqueInput
}

/**
 * Watchlist deleteMany
 */
export type WatchlistDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Watchlists to delete
   */
  where?: Prisma.WatchlistWhereInput
  /**
   * Limit how many Watchlists to delete.
   */
  limit?: number
}

/**
 * Watchlist without action
 */
export type WatchlistDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Watchlist
   */
  select?: Prisma.WatchlistSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Watchlist
   */
  omit?: Prisma.WatchlistOmit<ExtArgs> | null
}
