
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser.js'
export { Prisma }
export * as $Enums from './enums.js'
export * from './enums.js';
/**
 * Model Market
 * 
 */
export type Market = Prisma.MarketModel
/**
 * Model Trade
 * 
 */
export type Trade = Prisma.TradeModel
/**
 * Model Position
 * 
 */
export type Position = Prisma.PositionModel
/**
 * Model TraderStats
 * 
 */
export type TraderStats = Prisma.TraderStatsModel
/**
 * Model MarketPrice
 * 
 */
export type MarketPrice = Prisma.MarketPriceModel
/**
 * Model Watchlist
 * 
 */
export type Watchlist = Prisma.WatchlistModel
/**
 * Model Signal
 * 
 */
export type Signal = Prisma.SignalModel
/**
 * Model IngestionCursor
 * 
 */
export type IngestionCursor = Prisma.IngestionCursorModel
