
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma. Through it you get access to all the models, enums, and input types.
 * If you're looking for something you can import in the client-side of your application, please refer to the `browser.ts` file instead.
 *
 * 🟢 You can import this file directly.
 */

import * as process from 'node:process'
import * as path from 'node:path'
import { fileURLToPath } from 'node:url'
globalThis['__dirname'] = path.dirname(fileURLToPath(import.meta.url))

import * as runtime from "@prisma/client/runtime/client"
import * as $Enums from "./enums.js"
import * as $Class from "./internal/class.js"
import * as Prisma from "./internal/prismaNamespace.js"

export * as $Enums from './enums.js'
export * from "./enums.js"
/**
 * ## Prisma Client
 * 
 * Type-safe database client for TypeScript
 * @example
 * ```
 * const prisma = new PrismaClient({
 *   adapter: new PrismaPg({ connectionString: process.env.DATABASE_URL })
 * })
 * // Fetch zero or more Markets
 * const markets = await prisma.market.findMany()
 * ```
 * 
 * Read more in our [docs](https://pris.ly/d/client).
 */
export const PrismaClient = $Class.getPrismaClientClass()
export type PrismaClient<LogOpts extends Prisma.LogLevel = never, OmitOpts extends Prisma.PrismaClientOptions["omit"] = Prisma.PrismaClientOptions["omit"], ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = $Class.PrismaClient<LogOpts, OmitOpts, ExtArgs>
export { Prisma }

/**
 * Model Market
 * 
 */
export type Market = Prisma.MarketModel
/**
 * Model Trade
 * 
 */
export type Trade = Prisma.TradeModel
/**
 * Model Position
 * 
 */
export type Position = Prisma.PositionModel
/**
 * Model TraderStats
 * 
 */
export type TraderStats = Prisma.TraderStatsModel
/**
 * Model MarketPrice
 * 
 */
export type MarketPrice = Prisma.MarketPriceModel
/**
 * Model Watchlist
 * 
 */
export type Watchlist = Prisma.WatchlistModel
/**
 * Model Signal
 * 
 */
export type Signal = Prisma.SignalModel
/**
 * Model IngestionCursor
 * 
 */
export type IngestionCursor = Prisma.IngestionCursorModel
