
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models.js'
export type * from './prismaNamespace.js'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  Market: 'Market',
  Trade: 'Trade',
  Position: 'Position',
  TraderStats: 'TraderStats',
  MarketPrice: 'MarketPrice',
  Watchlist: 'Watchlist',
  Signal: 'Signal',
  IngestionCursor: 'IngestionCursor'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const MarketScalarFieldEnum = {
  conditionId: 'conditionId',
  question: 'question',
  category: 'category',
  outcomeA: 'outcomeA',
  outcomeB: 'outcomeB',
  status: 'status',
  outcome: 'outcome',
  closesAt: 'closesAt',
  resolvedAt: 'resolvedAt',
  volumeUsd: 'volumeUsd',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type MarketScalarFieldEnum = (typeof MarketScalarFieldEnum)[keyof typeof MarketScalarFieldEnum]


export const TradeScalarFieldEnum = {
  fillId: 'fillId',
  conditionId: 'conditionId',
  wallet: 'wallet',
  side: 'side',
  outcomeIndex: 'outcomeIndex',
  price: 'price',
  size: 'size',
  usdValue: 'usdValue',
  filledAt: 'filledAt',
  createdAt: 'createdAt'
} as const

export type TradeScalarFieldEnum = (typeof TradeScalarFieldEnum)[keyof typeof TradeScalarFieldEnum]


export const PositionScalarFieldEnum = {
  id: 'id',
  wallet: 'wallet',
  conditionId: 'conditionId',
  outcomeIndex: 'outcomeIndex',
  size: 'size',
  avgEntry: 'avgEntry',
  currentPrice: 'currentPrice',
  unrealisedPnl: 'unrealisedPnl',
  updatedAt: 'updatedAt'
} as const

export type PositionScalarFieldEnum = (typeof PositionScalarFieldEnum)[keyof typeof PositionScalarFieldEnum]


export const TraderStatsScalarFieldEnum = {
  wallet: 'wallet',
  tradeCount: 'tradeCount',
  resolvedTrades: 'resolvedTrades',
  winCount: 'winCount',
  winRate: 'winRate',
  realisedPnl: 'realisedPnl',
  roi: 'roi',
  avgEdge: 'avgEdge',
  score: 'score',
  firstTradeAt: 'firstTradeAt',
  lastTradeAt: 'lastTradeAt',
  updatedAt: 'updatedAt'
} as const

export type TraderStatsScalarFieldEnum = (typeof TraderStatsScalarFieldEnum)[keyof typeof TraderStatsScalarFieldEnum]


export const MarketPriceScalarFieldEnum = {
  id: 'id',
  conditionId: 'conditionId',
  outcomeIndex: 'outcomeIndex',
  price: 'price',
  capturedAt: 'capturedAt'
} as const

export type MarketPriceScalarFieldEnum = (typeof MarketPriceScalarFieldEnum)[keyof typeof MarketPriceScalarFieldEnum]


export const WatchlistScalarFieldEnum = {
  wallet: 'wallet',
  reason: 'reason',
  score: 'score',
  active: 'active',
  addedAt: 'addedAt',
  removedAt: 'removedAt'
} as const

export type WatchlistScalarFieldEnum = (typeof WatchlistScalarFieldEnum)[keyof typeof WatchlistScalarFieldEnum]


export const SignalScalarFieldEnum = {
  id: 'id',
  wallet: 'wallet',
  conditionId: 'conditionId',
  signalType: 'signalType',
  side: 'side',
  outcomeIndex: 'outcomeIndex',
  price: 'price',
  confidence: 'confidence',
  dryRun: 'dryRun',
  executed: 'executed',
  executedAt: 'executedAt',
  notes: 'notes',
  createdAt: 'createdAt'
} as const

export type SignalScalarFieldEnum = (typeof SignalScalarFieldEnum)[keyof typeof SignalScalarFieldEnum]


export const IngestionCursorScalarFieldEnum = {
  key: 'key',
  cursor: 'cursor',
  updatedAt: 'updatedAt'
} as const

export type IngestionCursorScalarFieldEnum = (typeof IngestionCursorScalarFieldEnum)[keyof typeof IngestionCursorScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]

